### ISSUE TITLE
Support opening links in a browser

### ISSUE THREAD

**Issue by bjorn3** [zulip/zulip-terminal#1030]
On Linux this can use `xdg-open <url>`. On macOS `open <url>` and on Windows `start "" "<url>"`.

**Comment by Ezio-Sarthak** [comment]
Hi! Thanks for the report. We already have an issue filed and open PR(s) for this: See the last checkbox of #452 and PR #991 for more insights. Hope this is the issue you're trying to address.

For more discussion, join the community on [CZO](chat.zulip.org) :) The stream dedicated to the terminal client is **#zulip-terminal** :)

**Comment by neiljp** [comment]
@bjorn3 Not sure if you saw https://github.com/zulip/zulip-terminal/blob/main/docs/FAQ.md#unable-to-open-links ?

Generally text links are selectable in a similar way, which should allow for copy/paste.

**Comment by bjorn3** [comment]
Yeah, that works (I need to shift drag to select and then middle mouse button to paste with xterm), but it is more work than just clicking on it or something like that.
