### ISSUE TITLE
All/everyone/stream mentions don't show up in mentions narrow

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#1037]
`@all`, `@everyone` and `@stream` mentions don't seem to appear in the mentions narrow.

I would recommend against testing the anomaly on any stream with a high subscriber count and would recommend using the zulip dev server.

**Comment by neiljp** [comment]
Also see #**zulip-terminal>Bug: "all" mentions** for original report and possible future discussion.

**Comment by preetmishra** [comment]
@neiljp Thanks for mentioning the stream and identifying the issue. 👍
