### ISSUE TITLE
add option to disable debug.log

### ISSUE THREAD

**Issue by mistersmee** [zulip/zulip-terminal#1066]
Currently, `debug.log` is created wherever the current directory is, and if there are no errors, it is a 0B empty file, even if zulip-term is launched without the `-d` flag.

I would like the creation of `debug.log` to be tied to that `-d` flag, as it gets messy and annoying after a while, deleting that file again and again, i.e. if the debug flag is passed then use debug.log, else don't create it.

If not that, then at least an option to disable creating that file.

**Comment by neiljp** [comment]
@mistersmee While I mainly run this from the same directory I definitely can agree with you on this :+1:
What version of ZT are you running?

We have a plan to move to using `xdg` directories which will help with this to some degree in future (#678).

However, independently of this plan, debug.log should have little output in most cases, so I'm going to see if there's a quick resolution to this where we don't create it until it's needed.

**Comment by mistersmee** [comment]
> What version of ZT are you running?

```
Zulip Terminal 0.6.0
```
> We have a plan to move to using xdg directories which will help with this to some degree in future (#678).

That would be awesome! I currently have an alias that basically does the same thing, `alias zul="zulip-term -c ~/.config/zulip-term/zuliprc"`, but having XDG support would make it so easier.

> While I mainly run this from the same directory I definitely can agree with you on this

I mainly stay in `~` as well, but sometimes I'm working in a repo, and I need to check messages I may have received, and it gets created there, etc. etc.

> However, independently of this plan, debug.log should have little output in most cases, so I'm going to see if there's a quick resolution to this where we don't create it until it's needed.

Sure, thanks! With that I'd say the issue is resolved, so I'll close it.

**Comment by neiljp** [comment]
@mistersmee Thanks for being proactive in closing this, but I'm going to reopen this for now to see if we can avoid outputting until we write to the file, like we do with other log-files, or until we have #678 resolved.

**Comment by neiljp** [comment]
@mistersmee Just a note that we keep the git version fairly stable and there are some good new features there you might enjoy :)
If you have time to drop by #zulip-terminal on chat.zulip.org it'd be interesting to hear your experiences with ZT and Zulip in general!

**Comment by neiljp** [comment]
@mistersmee I'm sure you'll get a notification this is resolved (by #1122) and now only opens the file in debug mode.
However, note that for now this is in only the git version - though this is very easy to install before we make the next release.

**Comment by mistersmee** [comment]
Pretty cool! This should help in keeping my homedir clean, thanks!
