### ISSUE TITLE
Enhance UX for User Info View (including custom profile fields)

### ISSUE THREAD

**Issue by Ezio-Sarthak** [zulip/zulip-terminal#1086]
ZT currently supports a basic version of the user information popup (press `i` in users list to open), with some trivial details of a user. However, we can improve its user experience further by:
 - ~~Displaying human-friendly last active timestamp. e.g., `5 hours ago`, instead of the formatted date string.~~
 - Displaying additional user information (e.g., favorite editor, status message, Github profile) as per a user's API response.

**UPDATE** Following brief discussion of this issue, it would seem that date rendering is best handled more uniformly, for which I've opened #1211 - and the web app doesn't currently show the `n hours ago` for users at the moment in any case? -- **neiljp**

**Comment by neiljp** [comment]
Closing this in favor of #1338, now that we have split the other issue out.
