### ISSUE TITLE
Newly installed version does not start due to missing "themes" package

### ISSUE THREAD

**Issue by JPTIZ** [zulip/zulip-terminal#1143]
There are a few problems actually.
1. Apparently the last release (0.6.0) used `platform.linux_distribution()`, so installing it would fail due to `platform` not having `linux_distribution()` anymore. To reproduce:

```console
$ pipx install zulip-term
$ zulip-term
```

(Pipx installs packages in an isolated virtualenv, similar to what is suggested on README.)

So creating a new release would be desirable.

2. So, to avoid using 0.6.0 and use `main`/latest, I've tried to do:
```console
$ pipx install git+https://github.com/zulip/zulip-terminal
```
But then running it leads to:

```console
Traceback (most recent call last):
  File "/home/jptiz/.git-configs/files/bin/zulip-term", line 5, in <module>
    from zulipterminal.cli.run import main
  File "/home/jptiz/.local/pipx/venvs/zulip-term/lib/python3.10/site-packages/zulipterminal/cli/run.py", line 14, in <module>
    from zulipterminal.config.themes import (
  File "/home/jptiz/.local/pipx/venvs/zulip-term/lib/python3.10/site-packages/zulipterminal/config/themes.py", line 6, in <module>
    from zulipterminal.themes import gruvbox, zt_blue, zt_dark, zt_light
ModuleNotFoundError: No module named 'zulipterminal.themes'
```

And, indeed, checking the module directory it doesn't have the `zulipterminal/themes` directory at all, althought it does have the [last commited change on `zulipterminal`](https://github.com/zulip/zulip-terminal/commit/2890a5d7c1dc2e8690c27dabee298ba3bc3071fe).

I remember fixing this manually before, but can't remember how.

**Comment by JPTIZ** [comment]
Ok, I remember how I fixed this: I cloned the repository separatedly, then copied the `themes` directory into the installed package's directory (`<virtualenv>/zulipterminal`).

**Comment by ElijahTheJew** [comment]
Also (another method, mostly related to running from source), when in the source code directory run: source zt_venv/bin/activate
This activates the virtual environment. You can then run zulip-term without issue.

**Comment by neiljp** [comment]
@JPTIZ Addressing the themes issue, this seems to be related to a missing `__init__.py` for that directory. That doesn't seem to affect local usage/installs, but certainly does affect `pipx` - I can reproduce the issue you had.

I've just pushed a fix for that to `main`, so if you'd like to try a fresh install from main that would be useful to test - it appears to work fine for me, but secondary confirmation is always good, especially from the reporter of an issue :)

Regarding the issue with 0.6.0, I believe we don't directly rely on the code you mentioned, so this could be a limitation of the `zulip` package, which may have been pinned for you locally for some reason to a low version and not work for the version of python you have installed (3.10)?

**Comment by JPTIZ** [comment]
> @JPTIZ Addressing the themes issue, this seems to be related to a missing `__init__.py` for that directory. That doesn't seem to affect local usage/installs, but certainly does affect `pipx` - I can reproduce the issue you had.
> 
> I've just pushed a fix for that to `main`, so if you'd like to try a fresh install from main that would be useful to test - it appears to work fine for me, but secondary confirmation is always good, especially from the reporter of an issue :)

And indeed it works :)

> Regarding the issue with 0.6.0, I believe we don't directly rely on the code you mentioned, so this could be a limitation of the `zulip` package, which may have been pinned for you locally for some reason to a low version and not work for the version of python you have installed (3.10)?

Right, I see it is a zulip-api version issue. I'll open a new issue just to address each problem on its place and let this one closed (solved).

---

Solved by https://github.com/zulip/zulip-terminal/commit/793e73d6de3f68551221b703582506a40a4bbbeb

**Comment by neiljp** [comment]
@JPTIZ Thanks for confirming 👍
