### ISSUE TITLE
Shortcuts menu cut off

### ISSUE THREAD

**Issue by lzmartinico** [zulip/zulip-terminal#1169]
On a small terminal screen (<100 columns), the shortcuts menu appears cut off, so that the actual shortcuts are not shown on the screen

**Comment by neiljp** [comment]
@lzmartinico Are you referring to those displayed in the help menu?

I seem to recall this was a problem for a few keys/descriptions in 0.6.0, though this should be fixed in `main` (though not if the terminal is resized while the menu is open).

**Comment by lzmartinico** [comment]
thanks, can confirm this is fixed in main (sorry for opening so many tickets without testing this first). Is there an ETA on a next release?

**Comment by neiljp** [comment]
@lzmartinico No problem at all with the tickets - we've gone a longer time than I'd hoped between releases. I have a changelog prepared for the next version, so I'm hoping to release "soon", but no specific date yet.
