### ISSUE TITLE
Feature request: Collapse sidebars

### ISSUE THREAD

**Issue by lzmartinico** [zulip/zulip-terminal#1170]
It would be useful to add a shortcut to hide the streams and users sidebars, to enable maximising the message view

**Comment by lzmartinico** [comment]
Thanks, autohide is a great approach for what I am looking for, and it made me discover a bunch of command line flags I wasn't aware of - maybe the README file should document these (or at least mention --help)?

**Comment by neiljp** [comment]
@lzmartinico We do have an entry for small terminals in the "FAQ" document which discusses this, which is linked from the README.

Would this small change help?
https://github.com/neiljp/zulip-terminal/tree/2022-03-17-add-help-option-to-README#configuration

**Comment by lzmartinico** [comment]
Yes, that looks great, thanks!

**Comment by neiljp** [comment]
@lzmartinico Thanks for your ongoing feedback; merged that small change :+1:
