### ISSUE TITLE
Where to download zuliprc?

### ISSUE THREAD

**Issue by xeruf** [zulip/zulip-terminal#1256]
The readme says:

> Your personal zuliprc file can be obtained from Zulip servers in your account settings in the web application, which gives you all the permissions you have there. Bot zuliprc files can be downloaded from a similar area for each bot, and will have more limited permissions.

But I can't find it on a self-hosted instance Version 5.2.

I could only find the documentation for bots: https://zulip.com/api/running-bots

**Comment by neiljp** [comment]
Hi @xeruf 👋 

Did you try the first approach in that part of the README? That should give a valid zuliprc file for you, though I'm guessing not if you already have one.

I agree our current documentation doesn't give that much detail for downloading the file from the server. I've posted an updated draft version at the link below, which should help you. Let me know if that is a good improvement for you and I can merge it to help others too 👍 

https://github.com/neiljp/zulip-terminal/tree/2022-09-15-improve-fetch-zuliprc-docs#running-for-the-first-time

**Comment by xeruf** [comment]
Ah I actually saw that section, but did not think I would be able to download it there. New Instructions are good :)

**Comment by neiljp** [comment]
@xeruf Thanks for the feedback :+1: Merging that fix today.
