### ISSUE TITLE
Generate hotkeys section/doc using script and check with CI

### ISSUE THREAD

**Issue by amanagr** [zulip/zulip-terminal#126]
All the keybindings used by zulip-terminal are stored in `zulipterminal/config.py`. We can generate README section of the hotkeys by travic CI.

We can create a different section for hotkeys that are imported from `urwid` and `urwid_readline` libraries.

**Comment by punchagan** [comment]
There should be a tool that developers can run locally, to generate this section of the README.  TravisCI should only check that any commit doesn't miss out on doing that, when keyconfig has changed in anyway. Some sort of a test can be run that compares the output of README when this script is run, and the README committed to the repo.

**Comment by neiljp** [comment]
I just thought this myself when opening #165 for some recent changes, and #164 for starred messages :)

**Comment by neiljp** [comment]
I believe we've discussed moving the hotkeys from README into docs/, so that might be a good first step, updating all the links, followed by the automatic synchronization via a script and then checking that with a GitHub Action (since we don't use Travis now).

**Comment by neiljp** [comment]
This is a similar issue to #892.

**Comment by mkp6781** [comment]
@zulipbot add "PR needs review"
