### ISSUE TITLE
Footlinks property is not allowed alongside maximum-footlinks

### ISSUE THREAD

**Issue by dmikushin** [zulip/zulip-terminal#1269]
While following the `zuliprc` configuration offered in https://github.com/zulip/zulip-terminal#configuration , the following error pops up in zulip-term:

```
Footlinks property is not allowed alongside maximum-footlinks
```

**Comment by neiljp** [comment]
This should be noted in the configuration block there:
```
# This option cannot be used with the footlinks option; use one or the other.
maximum-footlinks=3
```

Previously we had the footlinks option, then it was generalized to maximum-footlinks for finer control.

**Comment by neiljp** [comment]
@dmikushin Can we improve the error message you saw, or could we improve the documentation?

**Comment by neiljp** [comment]
Thanks for your feedback :+1:

#1283 should improve the situation, and will be merged soon. If you have feedback on that or anything else, please let us know.

**Comment by dmikushin** [comment]
Hi @neiljp , so sorry I've missed your question! Thank you for improving this, looks great :+1:
