### ISSUE TITLE
Improve debugging experience for zulip-terminal.

### ISSUE THREAD

**Issue by amanagr** [zulip/zulip-terminal#127]
Current developers can print variables in zulip-terminal which are logged in `/tmp/debug.log`. We can use `logging` module provided by python to log some of the data by default in `/var/log/zulip-term/error.log` and similar files.

@neiljp  FYI

**Comment by punchagan** [comment]
It is not common for non-daemon applications to log to `/var/log`. Commands run from the command line usually log stuff to a file in the current working directory.

**Comment by amanagr** [comment]
So, we can just log it in `/tmp/` directory?

**Comment by neiljp** [comment]
Is this now just a documentation issue?

We now have the traceback logging (for users & developers) but quite a few entries in the FAQ about it.

I recently raised that we could suggest using `flush=True` in the FAQ, so that outputs are written instantly (and to use perhaps `tail -f debug.log`), and we could restructure that part, and maybe split it into a 'developer' and 'user' section?

**Comment by amanagr** [comment]
Yeah, looks like we need to document the recent changes in logging. I would prefer moving the FAQ section to `wiki` section and yes we can make separate sections for users and developers there.

**Comment by neiljp** [comment]
While historically I was a proponent of wikis, personally I would prefer keeping it in the repo; if one makes a change in the code, it's easy enough to 'git grep' for affected changes (if the names are long enough), but that's not really feasible with a wiki.

**Comment by amanagr** [comment]
No problem! 😃

**Comment by neiljp** [comment]
See #299 for some rearrangement, if not significantly new content at this point.
(not including any migration from wiki)

Hmm, we should probably add a note about the traceback file in the README.

**Comment by neiljp** [comment]
@amanagr I plan to close this shortly as there may be ways to improve the experience, but we have a lot of docs now :)

**Comment by amanagr** [comment]
Yeah, go ahead!
