### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by Vincent-vst** [zulip/zulip-terminal#1281]
I tried to run zulip-term for the first time, but it can't find the Zulip URL.  
I downloaded it with `pip`  and I ran it with `zulip-term` using the terminal.   
It then ask me my zulip URL, (which works fine in my browser) but says : "Invalid Creadentials, Please try again!"  
The Readme says that it's probably coming from my self-signed certificate, but I'm not sure how to fix this.

**Comment by neiljp** [comment]
To confirm, do you definitely have a self-signed certificate?

If so then you will currently need to have a `zuliprc` file of some kind first, to add the details of where to find the certificate details, like the link to the Zulip docs in the README notes:
https://github.com/zulip/zulip-terminal#running-for-the-first-time

**Comment by Vincent-vst** [comment]
I'm still not sure that it's coming from my certificate but that's the most plausible options since the certificate also create problems with the desktop version.  
Do you know how can I add the certificate path to the `zuliprc` ?

**Comment by Vincent-vst** [comment]
I have this error when launching zulip with my zuliprc : 
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
```

**Comment by Vincent-vst** [comment]
I kinda fixed it with `insecure=true` in the zuliprc file

**Comment by neiljp** [comment]
As per the python-zulip-api docs linked from our README, if you have a self-signed certificate, you likely want something like:
```
[api]
key=<api key from the web interface>
email=<your email address>
site=<your Zulip server's URI>
insecure=<true or false, true means do not verify the server certificate>
cert_bundle=<path to a file containing CA or server certificates to trust>
```

**Comment by neiljp** [comment]
@Vincent-vst Have you managed to fix this securely?

Could we improve the documentation to make this clearer?

**Comment by Dhanwi** [comment]
> @Vincent-vst Have you managed to fix this securely?
> 
> Could we improve the documentation to make this clearer?

yeah, I think so, I am also getting the error regarding zuliprc (```
ERROR: Please ensure your zuliprc is NOT publicly accessible:
  /path/to/zuliprc
```)

**Comment by Vincent-vst** [comment]
@neiljp thank you, I've been able to run zulip-term

**Comment by neiljp** [comment]
@Vincent-vst Thanks for responding, I'm closing this since it's resolved :+1:

@Dhanwi This is not the same error, and is not related to this issue.
