### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by amanagr** [zulip/zulip-terminal#13]
Write tests for all the functions/classes in zulip-terminal.
Comment in this issue before you start writing tests for a function/class.
Look at [conftest.py](https://github.com/zulip/zulip-terminal/blob/master/tests/conftest.py) and [test_helper.py](https://github.com/zulip/zulip-terminal/blob/master/tests/helper/test_helper.py) for examples.

**Comment by DhruvThakker** [comment]
I would like to take this up. How should I approach it.

**Comment by amanagr** [comment]
In the long run, we would like to have special classes for easing the process of testing; but that would be too much for first steps. So initially you can create a directory `tests`:
```
tests
/test_ui.py
/test_model.py
/test_core.py
...
```
simply import the classes you are testing.
create a general sample data class for models.
This is what I think in general we want to do but let's wait for some feedback on this.
@timabbott

**Comment by amanagr** [comment]
I think now will be a good time to take this up since there wouldn't be major changes in code currently for 8 days for so since I am busy.
@DhruvThakker you should keep updating the status of the issue in a PR, so I can see how things are going.(can save you a lot of time.)

**Comment by neiljp** [comment]
From my perspective:
* pytest is likely the framework ZT will keep using
* if you've written other unit tests before, pytest is not that different
* start with whichever model you like, though ui testing involves a lot of mocking

Of course you're also welcome to chat on chat.zulip.org under #zulip-terminal for help on this :)

**Comment by neiljp** [comment]
To update this issue: coverage is now at 67% :)
That said, coverage does not expose all issues, but it's a good start :)

**Comment by neiljp** [comment]
Since we have fairly reasonable test coverage now, this is not high priority but may be worth keeping open as a pointer as to what to work on. It is highly unlikely that a particular PR will be considered to fix this issue.

**Comment by neiljp** [comment]
Coverage is now at 80% and we're typically including tests with new code, so I'm going to close this issue. If we later want to push coverage right up then I'd suggest we want a new issue in any case.
