### ISSUE TITLE
On login, providing zulip server prefixed by http:// or https:// manifests in incorrect username/password error

### ISSUE THREAD

**Issue by ahelwer** [zulip/zulip-terminal#1318]
On running zulip-term for the first time:
```
(zulip_terminal_pyvenv) [ahelwer@node ~]$ zulip-term
zuliprc file was not found at /home/ahelwer/zuliprc
Please enter your credentials to login into your Zulip organization.

NOTE: The Zulip URL is where you would go in a web browser to log in to Zulip.
It often looks like one of the following:
   your-org.zulipchat.com (Zulip cloud)
   zulip.your-org.com (self-hosted servers)
   chat.zulip.org (the Zulip community server)
Zulip URL: http://leanprover.zulipchat.com
Email: ahelwer@protonmail.com
Password: 

Incorrect Email(or Username) or Password!
```
I tried various times to paste in or manually type my password with the same result. Redoing things using `leanprover.zulipchat.com` instead of `http://leanprover.zulipchat.com` fixed things:
```
(zulip_terminal_pyvenv) [ahelwer@node ~]$ zulip-term
zuliprc file was not found at /home/ahelwer/zuliprc
Please enter your credentials to login into your Zulip organization.

NOTE: The Zulip URL is where you would go in a web browser to log in to Zulip.
It often looks like one of the following:
   your-org.zulipchat.com (Zulip cloud)
   zulip.your-org.com (self-hosted servers)
   chat.zulip.org (the Zulip community server)
Zulip URL: leanprover.zulipchat.com
Email: ahelwer@protonmail.com
Password: 
Generated API key saved at /home/ahelwer/zuliprc
...
```
Happy I managed to figure it out but it might be a good idea to improve the error message for usability!

**Comment by neiljp** [comment]
@ahelwer Thanks for reporting this bug!

#1320 should fix this sufficiently for the problem you mentioned. You don't say if you're using a stable or git version, in terms of testing it yourself, so please reply and confirm if possible if you're able to?

I expect to merge this once it passes CI, which will close this issue, but any feedback after that would still be helpful - and if you still find this to be an issue, please do reopen or open another issue :+1:

**Comment by ahelwer** [comment]
I'm on stable but can switch to git to test the fix later today!

**Comment by neiljp** [comment]
Just to note that this is a minimal fix, and I'm aware there are other cases that can fail right now. I'm looking into a larger refactor of this part which should enable more checks.
