### ISSUE TITLE
cannot narrow to 'pm_with'

### ISSUE THREAD

**Issue by Subhasish-Behera** [zulip/zulip-terminal#1351]
Due to recent changes in [zerver](https://github.com/zulip/zulip/pull/24775/),the narrow operator `pm_with` is not functional and ZT codebase needs to change it's occurrences to  `pm-with`.

**Comment by Subhasish-Behera** [comment]
@zulipbot add "PR needs review"

**Comment by Subhasish-Behera** [comment]
@zulipbot remove "PR needs review"

**Comment by neiljp** [comment]
@Subhasish-Behera Thanks for filing this 👍

We certainly will want to make this transition, and I believe it's backwards compatible, following the discussion elsewhere on chat.zulip.org.

**Comment by neiljp** [comment]
For the record, my understanding is that the change in the server has been updated to retain the backwards-compatible behavior that we were relying on, but this PR was useful to have in the interim and also looking forward.
