### ISSUE TITLE
Selection of muted stream does not update 'current' stream marked in search bar

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#138]
To reproduce:
a) Go to unmuted stream (eg. #announce)
b) Go to muted stream

Note how the stream/topic does not change and continues to show the #announce (or other) stream and topic.

**Comment by zee-bit** [comment]
@neiljp I can't seem to reproduce this. Is this issue fixed?

**Comment by neiljp** [comment]
@zee-bit This seems fixed to me - I think this was just a representation of how very early on we didn't show muted stream contents even if they were available? @amanagr @sumanthvrao Agreed?

**Comment by sumanthvrao** [comment]
Yup, it's likely that when we fixed that, we forgot to check and close this issue.

**Comment by neiljp** [comment]
@zee-bit Thanks for noticing this - closing this now :+1:
