### ISSUE TITLE
pip3 installation error on Fedora38: No matching distribution found for zulip-term

### ISSUE THREAD

**Issue by aurabindo** [zulip/zulip-terminal#1390]
python --version: 3.11.3

Installing via `pip3 install zulip-term` gives the following error on Fedora 38:
```
ERROR: Ignored the following versions that require a different python version: 0.3.1 Requires-Python >=3.4, <3.8; 0.4.0 Requires-Python >=3.5, <3.8; 0.5.0 Requires-Python >=3.5, <3.9; 0.5.1 Requires-Python >=3.5, <3.9; 0.5.2 Requires-Python >=3.5, <3.9; 0.6.0 Requires-Python >=3.5, <3.10; 0.7.0 Requires-Python >=3.6, <3.11
ERROR: Could not find a version that satisfies the requirement zulip-term (from versions: 0.2.0, 0.2.1)
ERROR: No matching distribution found for zulip-term
```

**Comment by neiljp** [comment]
As per the README, and PyPI page, the current release supports 3.6-3.10.

More generally see https://github.com/zulip/zulip-terminal/blob/main/docs/FAQ.md#what-python-versions-are-supported

**Comment by aurabindo** [comment]
Thanks for the info. I can close this ticket if there are other issues to track upgrade for 3.11

**Comment by neiljp** [comment]
@aurabindo 3.11 is supported in the current git branch, ie. `main`. It should be simple to install from there using a system like pipx, until the next release comes out, which will come straight from `main`.

So for now, if you're comfortable with that, please do give ZT a try using that approach - it should install just fine, and if there are other issues please do let us know :+1:

**Comment by aurabindo** [comment]
Installing zulip from git worked fine
