### ISSUE TITLE
Show user popup for sender of message on `u` hotkey 

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#1397]
This would match the behavior in the web app.

Look for the way in which this popup is opened from the user list, and apply the same approach but using the sender of message (only if one is selected).

Note that this is not `U`, which will be a key we use for marking unread, assuming we keep the same shortcut as in the web app.

**Comment by israelsgalaxy** [comment]
hi @neiljp , may i proceed with resolving this issue?

**Comment by brijsiyag** [comment]
@israelsgalaxy, If there is a "help wanted" label on issue, You can sure claim that by commenting `@zulipbot claim` and start working if someone is not working already.

**Comment by israelsgalaxy** [comment]
okay, thanks

**Comment by israelsgalaxy** [comment]
@zulipbot claim
