### ISSUE TITLE
Show online/offline status of users through different colors.

### ISSUE THREAD

**Issue by amanagr** [zulip/zulip-terminal#14]
We can use `'fetch_event_types':json.dumps(['presence'])` to get the present status of users.
Use different colors for `active` and `idle` status.

**Comment by kallepallimounikasmitha** [comment]
I want to work on this!

**Comment by amanagr** [comment]
@kallepallimounikasmitha I recently found out that we can user `'fetch_event_types':json.dumps(['presence'])` to get the present status of users.
I would like you to implement it using this method.
(this would require some experimenting with the data.)

**Comment by KurtovicUM** [comment]
hey, @bolognam and I are exploring this feature

**Comment by amanagr** [comment]
Thanks for your interest in this issue. Sorry, this issue has not been updated. 
This has already been partially implemented via #35. What you need to do to implement this feature is:
* Add 'presence' and 'realm_user' to https://github.com/zulip/zulip-terminal/blob/master/zulipterminal/core.py#L164.
* You will start getting updates regarding new users coming and leaving the realm. You need to update `model.initial_data` accordingly and use `model.get_all_users` to get the new list.
* Then re-render the user list with something like `model.users_view`. `model.update_reaction` and `model.update_messsage` are useful examples.

**Comment by KurtovicUM** [comment]
Sorry for what is probably a simple question, but how is user_realm defined? My understanding was that it'd be all users within the current stream, is that correct?

**Comment by kurianbenoy** [comment]
@KurtovicUM  are you till working on this issue?

**Comment by amanagr** [comment]
Yes 😅
