### ISSUE TITLE
Support old format for narrow links (subject in addition to topic)

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#1422]
As documented in buttons.py (currently `_parse_narrow_link`), we support links formatted in the form:
```
... narrow/stream/[{stream-id}-]{stream-name}/topic/{encoded.20.topic.20name}[/near/{message_id}]
```

As I noted in [**#api documentation > Narrow URL formats**](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/Narrow.20URL.20formats) this doesn't handle an old format where `subject` was used in place of `topic`, which makes the URL in the quoted message fail to be identified and link properly in ZT.

Servers running newer versions of Zulip will not generate links of this format, which limits the impact of this issue, but equally anyone who has upgraded an older server will potentially still have messages with links of this form.

**Comment by mounilKshah** [comment]
Given that nobody has claimed this issue so far, I'm working on it and hence, assigning it to myself.
