### ISSUE TITLE
Show hint for pressing SHIFT for selecting with the mouse.

### ISSUE THREAD

**Issue by aero31aero** [zulip/zulip-terminal#147]
Currently, trying to select anything with a mouse in zulip-terminal immediately deselects the text in xterm. The solution is to provide a hint for the following detail:

> Most terminal UI frameworks implement pressing SHIFT and then dragging to select text as you would expect (passing that mouse input to your terminal emulator).

I believe we do not have any use of selecting text in zt so far, so it could be possible to attach an event listener and then show a small message hinting them to use SHIFT and select.

Conversation that inspired the issue: https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/xterm.20copy.2Fpaste.3F

**Comment by neiljp** [comment]
Closed via #349.
