### ISSUE TITLE
Installing Error ( Add support for python >3.6 )

### ISSUE THREAD

**Issue by omi10859** [zulip/zulip-terminal#148]
Running zulip-term gives error 

>Traceback (most recent call last):                                      
  File "/Users/omkaryadav/Documents/project/zulip/evnterm/bin/zulip-term"
, line 7, in <module>                                                    
    from zulipterminal.cli.run import main                   
  File "/Users/omkaryadav/Documents/project/zulip/evnterm/lib/python3.7/s
ite-packages/zulipterminal/cli/run.py", line 9, in <module>              
    from zulipterminal.core import Controller                            
  File "/Users/omkaryadav/Documents/project/zulip/evnterm/lib/python3.7/s
ite-packages/zulipterminal/core.py", line 10                             
    from zulipterminal.helper import async                               
                                         ^                               
SyntaxError: invalid syntax

**Comment by amanagr** [comment]
Hi @omi10859, thanks for reporting, this appears to be an issue with python 3.7. In python 3.7 `async` becomes a keyword. A simple fix would be to rename the async function to something similar.
zulip terminal is not tested on python3.7, I would recommend using 3.6 instead.

**Comment by omi10859** [comment]
yeah, its working good in 3.6 
Can I take the task?

**Comment by omi10859** [comment]
@zulipbot claim

**Comment by amanagr** [comment]
sure!
