### ISSUE TITLE
Create extended user mention syntax when needed.

### ISSUE THREAD

**Issue by aero31aero** [zulip/zulip-terminal#151]
Recently, in zulip/zulip#10243 we merged support for the following mention syntax to zulip/zulip:

`@**Full Name|1234(id)**`

This is to allow us to mention users with the same full name, and is optional. The web app intelligently adds the new syntax only when the users have the same full name, and uses the simpler syntax for others.

Example: https://chat.zulip.org/#narrow/stream/7-test-here/topic/user.20mention

We should:

1. Add support for this syntax in the terminal client.
2. Ensure that it is behind a feature flag because it would break mentions in older servers/any non CZO server for now.

**Comment by timabbott** [comment]
We can do a check against the server version being 1.9.0 or greater, for this.

**Comment by zee-bit** [comment]
@neiljp This issue seems to be fixed by #854, should we close this?

**Comment by neiljp** [comment]
This is now likely pending on #928.

**Comment by zee-bit** [comment]
Ahh...sorry. It was user mention syntax and not the quoting syntax we recently merged. :)
