### ISSUE TITLE
Hotkeys interferring with Stream and Title fields

### ISSUE THREAD

**Issue by jakobkolb** [zulip/zulip-terminal#163]
When I write a message and fill out the Stream and Title fields, I am unable to type 'h' in the first and 'l' in the second field because they are interpreted as hotkeys and send me each to the other field respectively.

**Comment by neiljp** [comment]
Which version are you using? I don't see this behavior in master (development version).

I can use `r`, `c` or `@` and this doesn't appear to be an issue.

**Comment by neiljp** [comment]
@jakobkolb Thanks for the feedback regarding this bug!

@amanagr @punchagan I'm not sure of the process that was decided regarding releases; perhaps we can discuss on #zulip-terminal and release some kind of update for this and other issues being fixed?

**Comment by neiljp** [comment]
@jakobkolb Sorry for the delay, this should be resolved for the next release via #180 and ideally fixing #181 would pick this up in advance. Thanks for the feedback and please let us know if you have any other issues!

**Comment by neiljp** [comment]
@jakobkolb Just wanted to check that you're satisified with this issue now being closed?

**Comment by jakobkolb** [comment]
Yep, looks good. Thanks!

**Comment by neiljp** [comment]
Great, thanks for the reports!
