### ISSUE TITLE
Explore alternative key bindings for sending messages

### ISSUE THREAD

**Issue by feamsr00** [zulip/zulip-terminal#176]
Hi,
Um yeah, quick thing. On my platform `Alt-Enter` (meta-enter) is captured by my console host (for full screen). How does one customize the binding? As it seems right now, I have no way to send messages in this client. 🤷‍♂️ 

OS: Ubuntu 18.04 bionic [Ubuntu on Windows 10]
Kernel: x86_64 Linux 4.4.0-17134-Microsoft
Python: 3.6.6
Zulip-Terminal: Fresh from pip as of today (18-11-29)

While I'm asking, is there a better quit then ctrl-c?
Thanks!

**Comment by neiljp** [comment]
@feamsr00 For sending messages, you can explore `config.py` to customize the key bindings, specifically `SEND_MESSAGE` for your case. There were issues with configuring this with another value, so it would be useful to know what values you find work for you. #190 should allow ^S for updating star status (in addition to `*`), but I'm not sure the same approach will allow broadening to eg. `ctrl enter`.

My understanding is that currently ctrl-c is the normal way of exiting (I have always done so), though this should probably appear on the in-application help menu too.

**Comment by neiljp** [comment]
@feamsr00 I split the query/clarification of application exiting into #208, since this is a separate issue to be addressed.

Have you had any luck in alternative key-bindings? Latest master splits the keybindings into `zulipterminal/config/keys.py`, which is slightly easier to find, perhaps.

**Comment by neiljp** [comment]
This is planned to be worked around in the default install by adding ctrl-d as an additional send-message key in future, as per #263.
