### ISSUE TITLE
Implement icons via alternative font(s) for consoles with limited UTF-8/emoji support

### ISSUE THREAD

**Issue by feamsr00** [zulip/zulip-terminal#178]
Simple feat req. Use [NerdFont](https://nerdfonts.com/) To support some consoles that don't have great UTF-8\emoji support (yet). Thoughts?

**Comment by neiljp** [comment]
This sounds like a useful feature; I would appreciate pointers as to how this might be made to work.

If there are icons/aspects which do not currently render, please let us know the items and environment you're in, in a separate issue :)

**Comment by neiljp** [comment]
@feamsr00 Do you have experience with Nerdfont? See my earlier comment.

I also updated the title to better reflect your specific request.

**Comment by rht** [comment]
I have sifted through the internet, couldn't find any ways for a cli app to vendor in custom fonts. The only way to move forward with the glyphs is to either auto-detect the font support of a terminal, or provide an explicit flag to enable/disable glyphs.

**Comment by feamsr00** [comment]
Oh hello, let me wipe the dust off here :)

I do have experience as a NF user. I've used it powerline for zsh (via WSL) extensively. 

Truthfully the easiest way to get it to work, would be just that, detect if the is available (OS specific of course) and set a display flag to use them instead. As for including\redist the font, I'd either use a system package installer if you intend to use one which should allow that, or include in an "extras" dir that the user can optionally drop in themselves.

**Comment by rht** [comment]
For the powerline setup, IIRC there is a configuration parameter that can be specified by the user, e.g.
``
let g:lightline = {
  \ 'separator': { 'left': '', 'right': '' },
  \ 'subseparator': { 'left': '', 'right': '' }
  \}
```
This way, the user can use whichever unicode glyph they want. And no font distribution is required.
Then, there would be a documentation to describe how to install fonts which support displaying the specific unicode glyphs.

**Comment by amanagr** [comment]
This seems like a good idea to me. We can have a two configs - one with good emoji/glyph support and one without.

**Comment by neiljp** [comment]
To update this: we have started isolating the unicode we use into `config/symbols.py`, so in principle we could have "symbol themes" too at some point. As with regular themes and exposing them to be more easily configured, or keybindings (#680), my concern with this is that we start to tie ourselves into keeping the names/structure fixed.

For those installing from git, or willing to do so from a named (tagged) version, this does mean it should already be possible to adjust the symbol style to your liking, as long as we've not missed extracting a symbol into that file that you want to adjust :)

**Comment by neiljp** [comment]
@feamsr00 This was a great issue to understand the problem and possibilities for solution, but I'm closing this in favor of #938 which is expected to ultimately be the approach to be implemented to solve this :+1:
