### ISSUE TITLE
Ensure client_gravatar=True is always passed when appropriate

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#219]
I've not reviewed the other client code, but we generally use this flag to avoid the server computing and sending extra data that we don't need - we don't display any gravatars/icons.

There is at least one point in the code (at this time) which has a `False` being passed; while this is likely not overly significant, I'm not sure if there are other cases which should have this parameter actually passed.

This was discussed previously with @rht, but I wanted to have this open to track it. A simple fix is just one line to change the outstanding obvious parameter, but checking the others is potentially more work, if there is more to check!

**Comment by timabbott** [comment]
The `client_gravatar` flag is a significant bandwidth optimization, so definitely worth passing.  I think we need to pass this in both the `/register` and `GET /messages` queries.

**Comment by rht** [comment]
Maybe `client_gravatar=True` should be the default instead? Almost all API calls won't probably need the avatar except for a few GUI-based ones.

**Comment by rht** [comment]
Default as in it is what the server should assume.

**Comment by amanagr** [comment]
@rht I agree! but at this point, it's just a lot of work for everyone I suppose.

**Comment by rht** [comment]
@amanagr I'm more concerned about whether this will bite future API users. If `client_gravatar=True` is the default, any GUI-based API users will be able to see the 'error' early on by not seeing the gravatar, but with non-GUI-based API users, this manifests 'behind-the-scene' in the form of an increase in bandwidth consumption.
