### ISSUE TITLE
Users list: Names that are too long should be truncated to end with '...'

### ISSUE THREAD

**Issue by rht** [zulip/zulip-terminal#237]
On webapp:
![2019-01-03-233137_348x50_scrot](https://user-images.githubusercontent.com/395821/50667132-d7756800-0faf-11e9-8f63-04af2a574e5e.png)

Current ZT:
![2019-01-03-233255_322x63_scrot](https://user-images.githubusercontent.com/395821/50667169-ed832880-0faf-11e9-864b-a7699ac84ef7.png)

**Comment by neiljp** [comment]
This seems pretty straightforward, given the width details we managed before; I'll likely look at doing the same for the left sidebar too.
