### ISSUE TITLE
Crash creating new stream message in streams with no previous conversation.

### ISSUE THREAD

**Issue by sumanthvrao** [zulip/zulip-terminal#247]
The `c` Hot Key works in creating a new stream message works in streams which has previous conversations.  However the terminal crashes when used in streams which do not have any previous conversation. Expecting the Key to create a new message with stream set to current one and topic blank. 

Steps to reproduce bug in development environment (newest version) :
1. logged in as Iago@zulip.com
2. Use `c` in to create new messages in streams with no convo like #sales, #support 
3. ZT crashes with the following error message 
```
File "/home/sumanthvrao/.local/share/virtualenvs/zulip-terminal-sRIAC_7x/lib/python3.6/site-packages/urwid/container.py", line 1429, in _set_focus_position
    raise IndexError("No Pile child widget at position %s" % (position,))
IndexError: No Pile child widget at position 0
Zulip Terminal has crashed!
```
A workaround which avoids the error is to change `Stream` in message header (to #sales for example) when `c` is used to create new messages in streams with previous conversation.

**Comment by amanagr** [comment]
@sumanthvrao thanks for reporting this.
