### ISSUE TITLE
Add warning on startup if locale/language suggests missing "icons"

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#256]
At least one user reported that the screen had question marks or similar, and it turned out their locale did not include UTF-8.

We do note that eg. `en_US.UTF-8` is suggested in the FAQs, though I personally use `en_GB.UTF-8` and the drawing lines and so on all work fine. However, if I run `LANG=en_GB zulip-term` then the top lines are instead `????`, and the bullets for the top-left buttons and users are also `?`.

Given that we can detect the `LANG` setting by accessing the environment variables, we should be able to give a warning on startup that the icons/lines may be incorrect/unexpected.

Beyond this, in future we could aim to be adaptable:
- detect non-UTF-8 and use different characters for the top lines or bullets
- better font (UTF-16? some other way of detecting?) and use more complex icons

**Comment by amanagr** [comment]
From my past experience with urwid, I would say it's a bad idea to implement complex icons even if we detect UTF-16 support or better, since some characters are differently interpreted by different terminals on the same OS and they end up distorting display for ZT and you can't predict which icon may give you problems.

**Comment by neiljp** [comment]
@amanagr I was focusing this issue initially just on the UTF-8 issue with lines and bullets, though I do agree generally that this could get overly complex very easily.

That said, an alternative approach may be to generalize themes beyond colors to include icons (or have 'icon themes'), and keep the default theme as simple (and working!) as possible, while allowing other icons on more potentially-compatible displays?

**Comment by amanagr** [comment]
Even for a most capable system these factors are important in rendering a successful "icon theme":
* Font Used
* Terminal used (basically terminal input-output stream behaviour)
* OS
     - Windows -> No rendering icons / double width characters on WSL.
     - Linux -> I faced problem with Ubuntu 16 being able rendering an icon and Ubuntu 18 unable to in ZT.
     - Mac OS -> Works fine...

**Comment by neiljp** [comment]
There haven't been significant known issues related to UTF-8 in this way for some time that I'm aware of. As discussed in #**zulip-terminal>ZT crashing when scrolling down the user list** it therefore feels appropriate to close this issue now and remove the advice given in the FAQ. The latter will take place shortly in #979 (testing symbol rendering using shipped script + FAQ entry changes).

Given this decision I'm closing this issue, and as per the discussion mentioned above, this removes the need for #994, an intended fix.

The approach of icon themes has been isolated into #938 recently, which will likely be the longer-term solution to make the most of systems with minimal/typical/advanced icon/font/symbol support, and which is the expected solution to the problem described in #178.
