### ISSUE TITLE
Up button causes crash on muted streams.

### ISSUE THREAD

**Issue by sumanthvrao** [zulip/zulip-terminal#272]
Steps to reproduce issue:

1. Mute stream `bot testing` on `czo`.
2. Access stream in `zt`to find contents cleared for that stream. 
3. Using the 'Up'/k HotKey causes the exception.

Traceback of error: 
![error](https://user-images.githubusercontent.com/30312566/51447993-4a6d3580-1d49-11e9-8dc2-ae791d8bcd94.png)

**Comment by vishal-vardhan** [comment]
I don't know why but i couldn't reproduce the error following the steps @sumanthvrao suggested instead it shows a blank screen in the chat area ,same as said by @rht in #236.

**Comment by vishal-vardhan** [comment]
And mute is not working properly in `zt` ,it just shows blank screen.

**Comment by sumanthvrao** [comment]
I was unable to produce this in my development env. But by muting stream in `czo` as described in steps above, i was indeed able to reproduce it. Which one are you trying @vishal-vardhan ?

**Comment by vishal-vardhan** [comment]
@sumanthvrao  sorry i got late.yes i did the same thing as u did.moreover i think we can't mute a stream in `zt`.

**Comment by sumanthvrao** [comment]
@vishal-vardhan I just muted it in the web-client and then checked it in `zt`

**Comment by sumanthvrao** [comment]
@vishal-vardhan are you still working on this?

**Comment by sumanthvrao** [comment]
@zulipbot claim

**Comment by sumanthvrao** [comment]
@neiljp This issue no longer seems to occur. Trying to press Up/k HotKey in recent version of master is not causing a crash. Testing with the most recent version of master here.

**Comment by sumanthvrao** [comment]
Further discussion no this issue is here. 
https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Muted.20streams/near/701605

**Comment by neiljp** [comment]
Thanks to @sumanthvrao for their work on this! This should be resolved since we now show the content of muted streams, except if in the all-messages narrow.
