### ISSUE TITLE
Add functionality to check version from the command line

### ISSUE THREAD

**Issue by punchagan** [zulip/zulip-terminal#280]
`zulip-term --version` should print out the version of the terminal client.

**Comment by traintraveler** [comment]
@zulipbot claim

**Comment by rht** [comment]
Also, preferably, if on a git version, prints out `version+{git_short_hash}` (obtainable from `git describe`). This way it is unambiguous which version it is when reporting bugs.

**Comment by neiljp** [comment]
This looks great! My only thought is whether you'd like to include an extra line in `CHANGELOG.md` in the same commit (perhaps in the 'interactivity' section?) regarding the addition of this change?

Otherwise, I'm happy for this to be merged.

**Comment by rht** [comment]
I think `CHANGELOG.md` should be updated in bursts. Not every commit must touch that file.
