### ISSUE TITLE
Add 24-bit theme support

### ISSUE THREAD

**Issue by rht** [zulip/zulip-terminal#282]
This is a tracking issue for https://github.com/urwid/urwid/pull/284. Once merged, I will extend gruvbox to 24-bit, and also this will make adding other true color themes easier.

**Comment by tonycpsu** [comment]
@rht : I've merged the PR.  Can't say when a release will go out, but you can at least point to urwid master now.

**Comment by rht** [comment]
Finally!

**Comment by Ezio-Sarthak** [comment]
This would be as easy as adding a flag `2**24` in `--color-depth` argument.

We could also discuss here adding `88` too, though the default dark view for it doesn't seem readable at all :)

**Comment by neiljp** [comment]
Given the need for color-depth/theme compatibility after #998, I don''t mind if we leave this open to resolve the literal issue title, or close and break up into smaller issues - but I'd definitely like something open to track the incomplete support we're at right now, useful as it is already as an intermediate state :+1:

**Comment by neiljp** [comment]
I'm going to close this since we now support 24-bit features in themes, even if not every built-in theme has a 24-bit-specific set of colors - ie. we need to add those values to `DefaultColor` if we want them to be more specific.

See #T1069 for tracking follow-up.
