### ISSUE TITLE
Compact the help view

### ISSUE THREAD

**Issue by matrixise** [zulip/zulip-terminal#297]
Because the HelpView takes the complete size of my screen (this one is a 25"), I prefer to use a small interface for the shortcuts.

**Comment by neiljp** [comment]
Just to clarify, do you mean a small screen, or rather a certain text resolution?

I have a much smaller (laptop) screen, and with the extra lines currently present I can see all but one of the help lines. However, if the font was larger (and so there were fewer text lines) I could see that being an issue, but then we scroll anyway?

Could you describe the problem a little more?

I do think that removing the lines could be good, as long as we have something similar to address the matching by-eye of the actions to the keys, but I'd appreciate knowing your motivation in this case :)

**Comment by matrixise** [comment]
Hi @neiljp 
Here is a screenshot with the help.
![zulip-term](https://user-images.githubusercontent.com/38737/52778279-f6065e80-3045-11e9-9874-c43986293473.png)

**Comment by neiljp** [comment]
@matrixise This is not a match for the current development release - the menu is a lot more compact, at least horizontally. The current help looks more like the screenshots in #265 (merged ~18 days ago).

**Comment by neiljp** [comment]
@matrixise If you're willing to update your development copy, I'd appreciate if you'd consider whether we've reached a suitable level of improvement to close this issue, given the merger of your PR and #301.

**Comment by matrixise** [comment]
@neiljp I will do it asap (maybe tomorrow)

**Comment by neiljp** [comment]
@matrixise Just checking in with you regarding this issue.

**Comment by neiljp** [comment]
@matrixise I'm closing this for now since we've not heard from you and the help menu is dramatically changed.

If you have other suggestions/ideas, please open another issue or discuss on #**zulip-terminal** on chat.zulip.org.
