### ISSUE TITLE
Messages render as 'raw' rather than rendered, after they are edited

### ISSUE THREAD

**Issue by sumanthvrao** [zulip/zulip-terminal#308]
Steps to repro :
* compose a message in pm/stream with some block text (inside triple quotes or inline single quotes)
* Edit the message within block text while remaining on the same narrow ( From Webclient)
* The message now appears un-rendered on ZT. i.e re-rendering of edited block text messages are not happening. 
* reloading the narrow causes it to get re-rendered in the proper way. 

![bug2](https://user-images.githubusercontent.com/30312566/53058004-7231f380-34d7-11e9-94d9-971bf695f99f.png)

**Comment by sumanthvrao** [comment]
@zulipbot add "bug" "help wanted"

**Comment by neiljp** [comment]
@sumanthvrao Regarding the last point, what did you mean by 'reloading'? Reloading ZT? If I just switch between narrows then it doesn't re-render here.

**Comment by neiljp** [comment]
Edited the title to indicate that this includes other rendering, such as mentioning users.

**Comment by sumanthvrao** [comment]
I did a bit more digging into the issue and some stuff which i observed were :
* I edited a message containing mentioning users, block text and inline text. I changed only the inline part, however all the 3 kinds of messages got un-rendered. 
* @neiljp . I  originally tried this in a stream. Switching to another stream and returning back, renders the previously sent messages. I tried another message and for some reason it didn't render after switching. I tried with PM's now and it also does *not* render the messages upon returning back. Only  upon exiting ZT (`Ctrl+C`) and returning did the render get reflected. This is pretty weird!

**Comment by timabbott** [comment]
You folks may want to look at the webapp's algorithms in `message_list_view.js` for handling rerenders and ask questions about anything that's confusing (we'll add comments to clarify it).  I don't think the terminal app needs the same complexity around some performance optimizations, but certainly details like using separate field names for raw vs. rendered content and the logic is e.g. `merge_message_groups` and friends around computing what set of messages need to be rerendered when processing new messages being added/edited and processing a scheduled list of rendering changes in `render()` may be helpful.

**Comment by sumanthvrao** [comment]
Thanks for the advice @timabbott!

**Comment by sumanthvrao** [comment]
Most of the markdown rendering is done in `soup2markup` in `boxes.py`. From a quick look, `Updating_rendered_view` function in `model.py` is responsible for handling new content in rendered view.

**Comment by sumanthvrao** [comment]
@zulipbot claim

**Comment by sumanthvrao** [comment]
@neiljp FYI :)

Turns out this had a pretty simple. The un-rendered content was the input to `MessageBox` which did not render it thinking it was text.
