### ISSUE TITLE
Install via homebrew

### ISSUE THREAD

**Issue by gnzlbg** [zulip/zulip-terminal#320]
Is zulip terminal available in homebrew or could it be made available there?

**Comment by neiljp** [comment]
I'm not personally aware of this being the case, but am not familiar with this package system.

Our current tests run on a version of OSX in addition to Linux, but that uses pipenv/pip, not homebrew.

@gnzlbg Is homebrew the only system you would use? Have you managed to install using our recommended method?

**Comment by gnzlbg** [comment]
> Is homebrew the only system you would use? 

I wouldn't say so. I don't know if this makes sense, but if installing this would be as simple as `brew install zulip-terminal` or `brew install zulip-terminal --HEAD` (for installing the master branch) then I would have tried this already. 

I've written Python in the past so `virtualenv` and `pip` are familiar, but I haven't written Python in a while, and I remember that updating MacOSX, and having many versions of Python installed, choosing the right default ones, etc. wasn't "idiot proof" because MacOSX ships its own super outdated version of Python that always needs to be available. So for me having to worry about this is kind of a "barrier to entry", that's a bit unnecessary because homebrew handles all of this kind of automatically (the package says which python version it needs, and homebrew installs it if necessary and worries about the virtualenv stuff).

**Comment by neiljp** [comment]
I agree this would be a useful feature to have, and I'd expect we would accept packaging along these lines if someone was willing or able to work on it (having a mac/OSX is presumably a requirement). Do you have any input on this, @rht ?

That said, we depend only upon python 3.4+, and making and setting up a virtual environment has become progressively more standardized and easier over time - pip and the venv module are both included as standard in these versions.

**Comment by gnzlbg** [comment]
> having a mac/OSX environment is presumably a requirement

Yeah, adding a homebrew formula requires some testing, which is easy if one is using homebrew on osx, but I don't think it would be easy from linux.

**Comment by rht** [comment]
Having a "system" package always helps. Then brew formula would depend on having a `python3` (3.7) package installed. Then maybe it requires an executable with an explicit `$PYTHONPATH` pointed to brew's installation instead of the system's installation. I think the formula should be sufficiently generic that it should be straightforward to just pull from a python-based cli formula. I will have to check this.

**Comment by rht** [comment]
Update: most of the formulas I found require very few dependencies or just python2 or python3. It is already the case that homebrew no longer packages highly common libraries such as numpy/scipy (https://www.scipy.org/install.html). Even if there is a formula made for ZT, I doubt it will be included in the default package list, and anyone who wants to use the formula will have to do something along the line of `brew tap`. At the risk of polluting the namespace, maybe `sudo pip3 install zulip-term` is the fastest for now.

**Comment by rht** [comment]
For reference, cython: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cython.rb. There is another CLI app but it also depends only on having `python` installed.

**Comment by amanagr** [comment]
Thanks @rht for the reference. Looks like currently pip is would the best way to install zt. Closing for now.
