### ISSUE TITLE
Update user list after application is started

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#330]
The list of users in the right panel should be updated as the app finds out about it, as in the webapp.

Given the natural visibility of this panel in the no-autohide view (and an expectation it is the 'current' list of users) this seems like a high priority change.

**Comment by sumanthvrao** [comment]
@zulipbot claim

**Comment by sumanthvrao** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update users automatically](https://trello.com/c/CUyHQpSw/3-update-users-automatically)
