### ISSUE TITLE
Displaying streams' topics

### ISSUE THREAD

**Issue by shreyamalviya** [zulip/zulip-terminal#338]
As of now, when a stream is selected, one can not view the topics within the stream.
Based on the discussion on #zulip-terminal, these are some of the ideas we had to implement this:

- We could simply mimic this the way the webapp does. So in ZT, on selecting a stream, the list of topics would be displayed in a column. Perhaps a toggling approach where we would display topics in the left column itself would be a good idea. This would be somewhat analogous to clicking 'more topics' in the webapp -> displaying only topics -> coming back to stream view.

- A slightly different approach would be such that when the user selects a stream from the left column, there would be a small section (below the box which shows the current stream and topic in the current version) which would show recent topics of the stream. The user could switch to that section using some key and navigate through the recent topics. They could also view the list of all topics through something like *...* or *More* and then select whichever topic they want. 

Any insights or suggestions on this are welcome!

**Comment by shreyamalviya** [comment]
@zulipbot add "further discussion required"

**Comment by sumanthvrao** [comment]
Link to conversations related to this - 
* https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/rishi.20feedback/near/695843 
* https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Topics.20for.20streams/near/726783

**Comment by sumanthvrao** [comment]
@zulipbot claim

**Comment by sumanthvrao** [comment]
@zulipbot claim

**Comment by neiljp** [comment]
@shreyamalviya @sumanthvrao @amanagr The current implementation seems sufficient to close this now, though we could have a 'wide' view with streams in a separate column, when the screen width could fit it? We could file that as a separate low-priority issue?

**Comment by neiljp** [comment]
I'm going to close this now, as we have the implementation by @sumanthvrao from GSoC, and further issues could be opened if specific other features are required. If you disagree, please re-open, or chat on chat.zulip.org #zulip-terminal
