### ISSUE TITLE
Drop support for py3.4 & migrate to py3.5+ code and any new features

### ISSUE THREAD

**Issue by sumanthvrao** [zulip/zulip-terminal#360]
Py3.4 has reached End Of Life, upstream, making it reasonable for us to drop support for it.
This occurs as a result of third party packages (example: pygments, requests) having already stopped support for py3.4 in their latest release (on PyPI).  
There are various stages at which we could implement this transition : 
* [x] Removing it from CI
* [x] Changing the version requirements/suggestions
* [ ] Removing some simplifications that were also done due to python 3.4, and thinking around possible improvements using 3.5.

**Comment by rht** [comment]
This issue can be closed.

**Comment by neiljp** [comment]
@rht I think this was previously left open for the remaining element, namely removing python3.4 backwards-compatible entries. From memory, and checking the changelog, this is maybe mainly multiple-unpacking (https://www.python.org/dev/peps/pep-0448/), which I remember having to avoid when we had 3.4 included previously.

Do you know any tools that help with transitions like this?

**Comment by rht** [comment]
> Do you know any tools that help with transitions like this?

I doubt there is a tool that caters to a specific PEP change.

**Comment by neiljp** [comment]
@rht I was meaning for migrating between python versions, like for 2-to-3, but minor versions.
