### ISSUE TITLE
Events: Support stream pinning state changes

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#411]
Currently the pinned state updated in a different frontend only changes if we restart ZT. While this works for now - ZT is pretty quick to restart, and the stream is just in a different location in the interface - it would be useful to develop this. This would also allow addition of pinning/unpinning UI at a later stage.

This should be rather straightforward to add, though potentially needs consideration in the context of #410.

**Comment by kaustubh-nair** [comment]
@neiljp fixed in #695 ?

**Comment by neiljp** [comment]
@kaustubh-nair Could we maintain focus within the stream on pinning state change first? I erroneously referred to this as related to #617 in #]695, whereas this is stream-list related, not topic-list related. This is the #410-related aspect, where the focus changes unexpectedly just as the user is about to do something with the focused element.

**Comment by neiljp** [comment]
Catching up on this, this was effectively completed by #695, which also integrated existing stream muting events and updating into a UI in the stream popup, where they could be modified from ZT.

When #695 was merged, I left this open since there were related apparent issues.

One aspect of that was expanded into #747, to ensure that the stream popup data was synchronized with server data, if the latter changed while the popup was open.

The other is now expanded into #1487 so I'm closing this.
