### ISSUE TITLE
Quoting does not work

### ISSUE THREAD

**Issue by JasMich** [zulip/zulip-terminal#416]
I'm not sure if #402 or #239 want to tell the same.

If I type `>` to quote a message, HTML code appears in the reply box instead of markdown.

**Comment by sumanthvrao** [comment]
Thanks for the report @JasMich. I am working on improving this. :+1:

**Comment by JasMich** [comment]
Thank you! If you tell me how, I'd like to help as well. (I'm just not so known yet with `zulip-terms` source.)

**Comment by sumanthvrao** [comment]
@JasMich Definitely! You are welcome to claim this and give it a try.  

You can join the Zulip community development server where we have a stream (section) dedicated to the terminal app - https://chat.zulip.org/#narrow/stream/206-zulip-terminal is the link for it. Feel free to join us there.

**Comment by sumanthvrao** [comment]
@JasMich I am not able to reproduce this. For example, 
```
> hello

reply
```
Is working fine. Do you have a specific test case?

**Comment by JasMich** [comment]
No, I mean:

In the current thread, I select a message press `>` to quote the message (which was originally written in MD).

Now, In the reply box, you'll see the HTML code instead of the MD.

**Comment by sumanthvrao** [comment]
Oh, I think I understood.

The reply box (`compose` box) is supposed to contain the raw `HTML` form of the content, when you quote a message. But when you send the message (With 'Alt' + 'Enter'), it get's rendered into MD.

**Comment by amanagr** [comment]
@JasMich we have https://github.com/zulip/zulip-terminal/wiki/Developer-Documentation which should help you get familiar with zt's source code. Let me know if you need any help.

**Comment by neiljp** [comment]
@JasMich #409 includes tests for existing known working and failing tests, so if you do decide to work on this, that should provide some help with fixing this, though of course you'd be welcome to add to those tests too if that would help.

Regarding HTML in the compose box, that should have been fixed in git master, which has many fixes over 0.3.1 - I'm not sure if you stated which version you're using?
