### ISSUE TITLE
Toggle styling of reactions to indicate whether user has contributed

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#479]
This is visible in the webapp by a slight change to the style when toggling a reaction, and allows awareness of participation in a reaction when returning to older messages.

The idea of including something similar in ZT came from my comment on #476, ie. that we could achieve something similar by toggling the boldness.

This would avoid needing to go into the `i` menu to determine whether you have already reacted to a message, or toggling it to see if the count goes up or down.

This would probably be a follow-up to #476.

**see also an accidental duplicate in #512, which mentions an alternative styling**

**Comment by telescopic** [comment]
@zulipbot claim

**Comment by telescopic** [comment]
@zulipbot abandon

**Comment by blenderskool** [comment]
@neiljp This would be useful. As per #476 I agree with reserving bold styling to show whether a user has contributed to that reaction. We can make reactions a different color altogether in this case.

**Comment by neiljp** [comment]
I have an active solution for this, but have found a bug to fix in the meanwhile (#606) which is leading me to improve some of the tests first.
