### ISSUE TITLE
Keybinds: Same as web/electron?

### ISSUE THREAD

**Issue by mkaito** [zulip/zulip-terminal#50]
I feel like the key bindings should be the same across Zulip apps.

For example, I'm missing <kbd>j</kbd> and <kbd>k</kbd> greatly (my Ergodox keyboard has no arrow keys on the primary layer), but others are missing too. <kbd>J</kbd>, <kbd>K</kbd>, <kbd>A</kbd>, and <kbd>D</kbd> also seem pretty useful and should be around.

**Comment by amanagr** [comment]
@mkaito I added <kbd>j</kbd> and <kbd>k</kbd> keys via #51. I will add rest of them soon!

**Comment by mkaito** [comment]
Awesome!

It would probably also be a good idea to have a help pane on <kbd>?</kbd>, just like the web/electron app.

**Comment by amanagr** [comment]
#53 implemets <kbd>J</kbd>, <kbd>K</kbd> ; <kbd>?</kbd> will come later perhaps. I will implement <kbd>A</kbd> and <kbd>D</kbd> with <kbd>n</kbd> and <kbd>p</kbd> keys.
Thanks @mkaito

**Comment by punchagan** [comment]
Looks like #51 and #53 need to be documented in the README.

**Comment by mkaito** [comment]
Some others I've been missing:

* <kbd>q</kbd> to filter the stream list.
* <kbd>h</kbd> to replace left arrow; edit last message.
* <kbd>l</kbd> to replace right arrow.
* When in an input field, prepend `hjkl` with Ctrl for movement.
* <kbd>G</kbd> go to last message in view.
* <kbd>/</kbd> to search.
* <kbd>P</kbd> narrow to private messages.

But, in general, it should use the same keys as the desktop/web app where possible.

**Comment by amanagr** [comment]
@mkaito Urwid has problems with `Ctrl` + `j` and `Ctrl` + `h` for implementing movements in an input field. So, we are planning to go for `meta` with `hjkl` for movement in an input field. Do you have any suggestions or other keys you would like to suggest?

**Comment by neiljp** [comment]
What's the current status of this? Most of the keys and issues I can see here are resolved?
@mkaito Do you have any feedback on this?

**Comment by amanagr** [comment]
I think it's a good time to close this issue. @mkaito you can reopen this issue if you need to give any feedback or suggestions. Thanks!
