### ISSUE TITLE
Other linters/fixers or tools to improve code style/consistency

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#508]
We currently have a reasonable linting setup to run locally and in CI, so this is not highly important,  but worth tracking - and discussing on #zulip-terminal. See the `Linting/formatting` topic for some past discussion.

Note that there are linters and (re/auto)-formatters, and not all tools do both, or cover the same feature-set.

Tools to consider so far:
* **autopep8** (reformats based on pycodestyle rules)
* **zulint** - @amanagr helped to extract the linting tool from the server repository into an external project (https://github.com/zulip/zulint) last Sumemr; this can incorporate external linters including pycodestyle
* **flake8** (and plugins, eg. bugbear)
* **black** (auto formatter) - many projects are using this, but it notoriously lacks configuration!
* **pylint** - this is very configurable, but can be slow?

**Comment by neiljp** [comment]
`autopep8`, `autoflake` and `flake8` are now dev dependencies, although only the latter is in CI as the others are code fixers.

We also use flake8-continuation and flake8-quotes.

There has also been talk of using `codespell` in the zulip/zulip repo, and I've applied it on occasion, eg. the updated merged commit in #881, but also notes in the former that it may be not so simple to add to CI.

**Comment by timabbott** [comment]
Now that the server project has moved to black, it's probably a good idea to migrate this too.

@andersk may be able to help with tooling for making it easy to rebase PRs.

**Comment by neiljp** [comment]
We now use a lot of standard linting and fixing tools that are well integrated, including most of the above tools or faster versions, so I'm closing this issue in favor of any issues for specific improvements.
