### ISSUE TITLE
Exiting search from filtered Stream/User list should reset PanelSearchBox

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#536]
This seems to work fine with topics, but not with streams/users?

To reproduce:
* enter search box (w or q, or probably clicking in the box too)
* enter search text
* press 'enter' to go into the filtered list
* press 'esc' to clear the search

Expected: The search box resets (to show eg. `Search [q]:`)

Actual: The search box shows the old text - the previous hint that this was a search box is lost, as well as the key to do the search.

**Comment by preetmishra** [comment]
@zulipbot claim
