### ISSUE TITLE
Allow scrolling of large single messages

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#543]
Depending on the size of the terminal window, which in turn limits the size of the message list area, certain large messages cannot be viewed in full.

If only a part of a message is being displayed, then we could probably respond to up/down as scrolling through the message only, or perhaps have slightly different keys to do so? We might not want to jump to the next message by 'accident', which could happen if we use regular keys, and different in-message navigation would solve that. A scrollable 'pop-up' for the full message could be another option here.

The maximum message size should be available in the server repo.

**Comment by preetmishra** [comment]
The way Zulip's web app handles long messages is by limiting the size of the message (that is going to be displayed in the narrow) and using a `[More...]` button. 

I think it'd be a good idea to imitate this behavior in ZT. We could limit the message size and append 'Press `m` to see more' to the message, where pressing `m`  would launch a scrollable full message pop-up.

**Comment by neiljp** [comment]
@preetmishra This looks like a reasonable first approach at the very least.

This has come up again, since I realized it might be useful to have for wide text, like with code blocks, for which https://github.com/zulip/zulip/pull/14706 may be relevant.
