### ISSUE TITLE
Download emoji list from server

### ISSUE THREAD

**Issue by kaustubh-nair** [zulip/zulip-terminal#558]
We currently use a list of emojis from zulip's repo to display emoji typeahead. These emojis maybe different for different servers, hence they need to be downloaded from `static/generated/emoji/emoji_codes.json` 

We will require a public API endpoint for downloading this; a little bit of discusstion is present here https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Getting.20emojis.20from.20server

**Comment by kaustubh-nair** [comment]
@zulipbot add "enhancement"

**Comment by neiljp** [comment]
The API endpoint for this exists as of v6.0, so closing this in favor of the more up to date #1250.
