### ISSUE TITLE
Invisibile selection bar on exiting search

### ISSUE THREAD

**Issue by kaustubh-nair** [zulip/zulip-terminal#580]
Trying to go to any of the side-panels after an unsuccessful search doesn't show the selection bar.

Steps to reproduce:
1. Search for something that has no matches.
2. Press `h` or `l` to go to one of the side-panels.
3. Selection bar is missing. (However the selection bar reappears when pressing `j` or `k`)

**Comment by kaustubh-nair** [comment]
@zulipbot add "bug"

**Comment by neiljp** [comment]
This would be fixed via something like #278.

**Comment by neiljp** [comment]
Closing in favor of #1506, which is the general case.
