### ISSUE TITLE
Show & autocomplete PM recipient names & emails

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#587]
Currently only emails are shown in PM 'to' fields when sending a message. The server is moving towards hiding emails optionally or fully (preferring user-ids, see #579), but even if this was not the case, while showing email addresses is unique, email addresses don't always easily translate to an obvious name.

The simplest (if verbose) solution to this would be to do something like in email, ie. `Some Person <somebody@example.com>`. We should discuss others.

Any `user_id` changes underneath could be separate.

**Comment by neiljp** [comment]
Stream/topic work is mostly complete as-of #746, so improving PM input/display is a high priority.

**Comment by neiljp** [comment]
See #586 for more discussion on this.

**Comment by prah23** [comment]
I see that this hasn't been worked on yet, I'd like to take this up.

**Comment by prah23** [comment]
I see that this hasn't been worked on yet, I'd like to take this up.

**Comment by prah23** [comment]
I see that this hasn't been worked on yet, I'd like to take this up.

**Comment by prah23** [comment]
I see that this hasn't been worked on yet, I'd like to take this up.

**Comment by prah23** [comment]
I see that this hasn't been worked on yet, I'd like to take this up.

**Comment by neiljp** [comment]
@prah23 You're welcome to take this up :+1: It would be good hear your plans for the UI.
