### ISSUE TITLE
Reactions can show differently in multiple places

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#599]
Some reactions appear to show differently below messages and in the message-info box - and also possibly compared to in the webapp (on hover, for the name).

This looks confusing and like a major bug, even though it typically shows at least a similar reaction, so we should probably figure this out - it just looks bad.

This may be related to data which we don't directly have? @kaustubh-nair

**Comment by mregdos** [comment]
I tried adding some random reactions via webapp and I am seeing the same reactions both below messages and within message-info box in ZT. Do you have an example of incorrect behavior?

**Comment by kaustubh-nair** [comment]
@mregdos try `:fingers_crossed:`
This is likely caused due to the `emoji` package we're using.

**Comment by preetmishra** [comment]
@mregdos You can see this test -https://chat.zulip.org/#narrow/stream/7-test-here/topic/test.20reactions/near/85559, in particular.

**Comment by preetmishra** [comment]
Related conversations:
* https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/.3Acrossed_fingers.3A/near/848945
* https://chat.zulip.org/#narrow/stream/3-backend/topic/Mismatch.20between.20emoji.20and.20reaction.20names/near/855678
