### ISSUE TITLE
Amend help text to indicate new autocomplete support for emojis

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#604]
With #525 merged, Zulip Terminal now supports autocomplete for emojis. However, the help text doesn't reflect this change.

This should be pretty straightforward to fix (for related code, look in `zulipterminal/config/keys.py`).

##### Screenshot:
![image](https://user-images.githubusercontent.com/43616959/79695831-9f726100-8296-11ea-96bb-79e2aa29fa37.png)

**Comment by preetmishra** [comment]
@zulipbot add "enhancement" "good first issue"

**Comment by neiljp** [comment]
This is a good first issue, but we should fix before the next release; I'm going with 'high priority' for now.
