### ISSUE TITLE
Handle narrowing to empty streams in a better way

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#607]
Currently, narrowing to empty streams makes the selection bar disappear. Moreover, it is difficult to make out why nothing is being shown in the MessageBox.

**To reproduce**:
* Navigate to an empty stream (e.g. Django on chat.zulip.org).
* Press enter.

We could try imitating the web and the mobile app that show a rather informative message, when narrowed, for these streams.

Another aspect, related to narrowing to empty streams, has been discussed in #259.

**Comment by preetmishra** [comment]
@zulipbot "enhancement" "help wanted"

**Comment by preetmishra** [comment]
@zulipbot add "bug"

**Comment by preetmishra** [comment]
@zulipbot add "bug"

**Comment by neiljp** [comment]
@preetmishra This may be resolved by a relatively early PR (#278) from @sumanthvrao? That PR has been sitting around without getting merged for too long, but should be good as a starting approach after rebasing and final reviews. We could potentially take a different approach, of course.

**Comment by preetmishra** [comment]
@zulipbot add "bug"

**Comment by neiljp** [comment]
Closing in favor of #1506, which is the general case.
