### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by andreas-bulling** [zulip/zulip-terminal#611]
Hi,

I followed the installation instructions but trying to login to the latest version of zulip on our own server using zulip-terminal results in the following error

```
Welcome to Zulip.
Loading /
Error connecting to Zulip server: Invalid API key (get_messages, register).
```

Both the desktop app and the browser login work.

What's strange: When I download the zuliprc from "Settings" the API key is the right one/the same but the email address is different. It's not the one shown in the account details but a generic user2@ourcorrectdomain.tld

**Comment by amanagr** [comment]
If you remove your `zuliprc` file, you will be asked to input your `email` and `password`, along with `realm`, can you try login using that? It will also generate a zuliprc file for you. Remember if you haven't setup your password for the zulip account, you can do so by using reset passwork on browser.

**Comment by andreas-bulling** [comment]
That's what I did first - didn't work. Then I downloaded the zuliprc file from "Settings" and noticed the differences. That file also doesn't work though. I definitely have a passwort - it comes through LDAP and works when logging in using the desktop app/browser

**Comment by amanagr** [comment]
Can try creating an account on chat.zulip.org and see if it works? In case it works, this maybe a problem with your org. In that case, please describe your org and the zulip version it is running on.

**Comment by andreas-bulling** [comment]
I just had to use a different email address. This is currently a bit confusing, I find, as there is the actual one from LDAP and the userX@hostname one Zulip creates

**Comment by neiljp** [comment]
@andreas-bulling Glad you managed to resolve this :+1: However, which email address did you have to use? The Zulip one? This may be related to a new feature in the server which hides email addresses and replaces them with local ones for privacy reasons, depending on how the server is set up - so it would be good to know what was necessary and what your server setup is. We can update the documentation if you can give a little more feedback, eg. what emails were where, and what one worked.

**Comment by andreas-bulling** [comment]
I had to use the real one, i.e. the one from LDAP. I just tried - this is independent from whether the server is configured to hide email addresses or not.
