### ISSUE TITLE
Make list of themes available explicitly

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#613]
Currently, users likely use just the default theme, unless they examine the source to see the themes in `config/themes.py` - and that will be buried in a virtualenv somewhere, most likely.

Improvements we should likely make include at least:
* include a mention of themes somewhere in the README
* add a command-line option to list the known themes (`--themes`, or perhaps the more obvious `--list-themes`?)

**Comment by sumagnadas** [comment]
What is needed to be done for this except for adding a command option that lists all the available themes using `all_themes()`?

**Comment by sumagnadas** [comment]
@zulipbot claim

**Comment by sumagnadas** [comment]
> @zulipbot claim

Is zulipbot not working or is it because i haven't made any contributions to this repository before?

**Comment by neiljp** [comment]
I believe zulipbot is not working right now. It's clear you're working on it :+1:
