### ISSUE TITLE
Maintain position in topic list when toggling topic list

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#617]
When we enter/leave the topic list, we currently reset the focus in the topic list to the top - even if previously it was some distance down the list.

I'd suggest we want to maintain focus instead, perhaps even when moving between different streams and back again? (at least, within one ZT session)

For implementation, this will involve storing the state when last in a stream (if there is any), on changing between stream and topic views in the left panel. Note that topic names and ordering may change between such times, so we should also fall back to an almost match, including if a topic is resolved.

**Comment by Subhasish-Behera** [comment]
@neiljp i would like to work on this issue as my first issue.can u point me to the directory where changes are needed to be made?

**Comment by neiljp** [comment]
@Subhasish-Behera This will likely be a change in one of the ui_tools/ files, maybe `views.py`.

I'd suggest generally understanding the logic involved in following from a 'key' (eg. `?` for the help menu) to the action, and then which state it updates.

If you need support with getting started, please drop in on chat.zulip.org in #zulip-terminal :)

**Comment by Subhasish-Behera** [comment]
@israelsgalaxy Thanks for showing interest in ZT.Thanks for showing interest in ZT. I've made substantial progress and am almost finished. Given the progress I've made, I think it would be best for me to wrap this up, and you could work on a different issue.
Sorry if there was some confusion as I don't generally `claim` any issue .

**Comment by neiljp** [comment]
Fixed by #1277.
