### ISSUE TITLE
Indicate if a user-activated operation failed

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#620]
Currently many operations such as starring, reacting, sending messages - all just fail with no feedback if the server fails to respond.

If just for debugging purposes, we should at minimum show a simple popup (as a v1) to indicate to the user that something has failed, and potentially in what way.

We could then extend that into a general approach to this subsequently, unless we have a strong feeling about taking that route first.

**Comment by kaustubh-nair** [comment]
@neiljp fixed in #714?

**Comment by neiljp** [comment]
@kaustubh-nair #714 seems reasonable as a first solution, certainly :+1: Thanks for digging this up.
