### ISSUE TITLE
Don't mark as read on search narrows

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#624]
Like the web app, ZT should not mark messages as read on search narrows to deliver a better and intuitive user experience.
This should be a good starting point for implementing any 'not-reading' behaviour in ZT (see #585).

Conversation link: https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Not.20marking.20read

**Comment by preetmishra** [comment]
@zulipbot add "enhancement" "help wanted"

**Comment by neiljp** [comment]
This might also include where we 'jump' to another narrow in a way that the user is unsure what they will see, equivalent to going to a 'near:' narrow in the webapp?
