### ISSUE TITLE
Footer gets updated as many times as the edit key is pressed on any uneditable message

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#647]
Steps to reproduce:
* Move focus to any message that you can't edit
* Press e multiple times
* Press any other key to trigger the behaviour

**Comment by neiljp** [comment]
To clarify, for me it updates the footer multiple times with different help hints, after the error message stops being displayed.

**Comment by neiljp** [comment]
Also, this doesn't require the last key for me - just wait, and it will update the bottom bar rapidly after the timeout.

**Comment by kaustubh-nair** [comment]
@neiljp @preetmishra What is the expected behaviour here?

**Comment by preetmishra** [comment]
@kaustubh-nair The footer text should only get updated once after the timeout.

**Comment by neiljp** [comment]
Agreed, this seems fairly obvious from manual testing.
