### ISSUE TITLE
Tidy up white space in StreamInfoView

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#654]
The mentioned popup/view show a blank line after the content which isn't as pleasing to look at. We could either remove the blank line or add a blank line at the top for consistency.

For comparison, look at the help menu (it doesn't have any unnecessary blank lines).

**Comment by preetmishra** [comment]
@zulipbot add "further discussion required" "UI"

**Comment by neiljp** [comment]
While we can tidy this, I think really what we can do with this is extend this popup to show more information generally, and also use it as a location for less common (or all) stream actions, ie #570.
