### ISSUE TITLE
Enhance the general popup styling

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#684]
We could improve the general popup styling to make popups stand out a bit more from the rest of the view.

This may involve a bit of experimentation, exploration and discussion with the team. Feel free to drop a message in [#zulip-terminal > Popup Styling](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Popup.20Styling) about your design proposal. The related conversation should be in the mentioned topic.

The relevant code should be in `zulipterminal/config/themes.py` and `zulipterminal/ui_tools/views.py`.

**Comment by neiljp** [comment]
Anyone interested in this is also welcome to drop here some screenshots showing alternative designs which we can discuss and give feedback on.

**Comment by vinitwadgaonkar** [comment]
i am intrested

**Comment by neiljp** [comment]
Fixed by #853 :tada: Thanks @Ezio-Sarthak :+1:
