### ISSUE TITLE
key error in `helper.py` on start

### ISSUE THREAD

**Issue by ExpandingMan** [zulip/zulip-terminal#694]
On starting `zulip-term` I get the following error
```
ERROR:root:225542
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/zulipterminal/cli/run.py", line 296, in main
    Controller(zuliprc_path,
  File "/usr/lib/python3.8/site-packages/zulipterminal/core.py", line 43, in __init__
    self.model = Model(self)
  File "/usr/lib/python3.8/site-packages/zulipterminal/model.py", line 115, in __init__
    self.unread_counts = classify_unread_counts(self)
  File "/usr/lib/python3.8/site-packages/zulipterminal/helper.py", line 414, in classify_unread_counts
    if [model.stream_dict[stream_id]['name'],
KeyError: 225542
```
As you can see, this is with Python 3.8.  This is on manjaro with zulip-term 0.5.1 installed via `pip`.

**Comment by neiljp** [comment]
@ExpandingMan Do you have a lot of streams/organizations on your server? Is this on zulipchat.com? That's a high stream id!

Regarding the specific bug, my suspicion is that we're not handling the case where you were initially subscribed, gained unread messages, then unsubscribed, so the unread details don't appear in that dictionary.

As a workaround, if my suspicions are correct: if you recently unsubscribed, one option may be to just re-subscribe, if that's feasible. If you don't wish to stay subscribed, you might mark everything as read and quickly unsubscribe (in eg. webapp). Of course, if you wish to keep your unread counts then that's not going to work for you.

Let us know if you use the workaround to any satisfaction, as it would also go some way to confirming the source of the issue.

**Comment by ExpandingMan** [comment]
If the stream ID's are ordered rather than hashed, then I suspect the stream ID itself is in error.  This is on `julialang.zulipchat.com`, I don't think we have a particularly high number of streams.

If I'm understanding what you're saying correctly, it sounds like there is some stream which I am unsubscribed from on which I have unread messages and that you think this somehow leads to the error.  While that may well be, unfortunately I am not even sure which streams I had previously subscribed to but since unsubscribed from.  I therefore can't implement this workaround unless I have some way of seeing that.

**Comment by neiljp** [comment]
While there may not be many streams on the julialang zulip, the ids could be higher since this is on `zulipchat.com`, by my understanding.

I'm not sure how comfortable you are with the source and/or python, but from the code this would be in the `Model`, in `self.initial_data['unsubscribed']`, though I haven't worked with that data significantly. If you did a `print(...)` of that near the end of the `Model` `__init__` then you may find it out. You may be able to determine something similar from inspecting network traffic or similar when the webapp connects. Otherwise, I'm afraid we'll just have to fix the bug - I've marked it as important for our next release!

**Comment by ExpandingMan** [comment]
I was going to hop in to it with a debugger, look what's going on and let you know.  Unfortunately, I'm finding Python environments to be just as irritating as ever and simply running from the cloned repo without doing anything else resulted in a rather spectacular crash of the entirety of X windows that required a display server restart, so not quite sure what happens there.

Anyway, most likely I'll wait for you guys to do some sort of patch and then check it again.  Thanks!

**Comment by neiljp** [comment]
Oh wow, that's not good! Maybe down to the debugger using lots of memory? Just a guess.

**Comment by ExpandingMan** [comment]
No nothing like that, something with alacritty goes haywire I think.  Might be worth trying again, I wouldn't worry about it.  The key error is a clear problem, this probably isn't.

**Comment by neiljp** [comment]
@ExpandingMan #706 should be a simple fix for this and is in the main branch now - it will be in 0.5.2, but if you wish to test the development version and see if this fixes the issue for you too this would be useful to know. Thanks again for reporting!
