### ISSUE TITLE
Muting and unmuting stream causes errors in unread counts.

### ISSUE THREAD

**Issue by kaustubh-nair** [zulip/zulip-terminal#696]
If a stream is muted, reading messages after unmuting it causes negative unread counts.

**Comment by neiljp** [comment]
@kaustubh-nair I understand that code is missing here, as we discussed, but could you describe a way to reproduce the bug you're describing? On master I see the stream count go down one at a time as I read messages, for example, after unmuting a stream that was muted when I start ZT. What is different/specific in this case?

**Comment by kaustubh-nair** [comment]
@neiljp The key point here is to mute and then unmute the stream after you start ZT. It will not cause problems if the stream was muted before starting because `unread_counts['streams'] ` was updated by `classify_unread_counts`
