### ISSUE TITLE
Introduce new prefix character for web public streams

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#712]
Currently, both the web public streams and the public streams use '#' as `prefix_character` which makes it hard to portray the distinction. To resolve this, we could either use 'W' (considering how 'P' is used for private streams) or some other character for the web public streams.

#### Screenshot

| Web app | Zulip Terminal |
| ------------ | ------------------- |
|![image](https://user-images.githubusercontent.com/43616959/86891138-fceeaf00-c11b-11ea-8890-e8d3f430bfd6.png) | ![image](https://user-images.githubusercontent.com/43616959/86891492-8f8f4e00-c11c-11ea-8663-2b6c9d88146d.png) |

**Comment by preetmishra** [comment]
This not critically important for now but would be useful to have post https://github.com/zulip/zulip/pull/14638.

**Comment by neiljp** [comment]
This is covered in more detail by the broader but duplicate #1135.

**Comment by neiljp** [comment]
This was fixed by #1177.
