### ISSUE TITLE
IDEAS: Improve recipient (narrow) rendering

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#719]
This is intended to address the styling of:
* headers above each (group of) message(s) in a stream/all/mention/... narrow
* the 'current message recipients' contents
* the 'navbar' at the top of the central column, specifying the narrow

Aspects that have been discussed previously to my knowledge:
* adding a `#` before stream narrows #**zulip-terminal>Stream prefixes (messages)**
* adding a space before/around that, and before other text, to indent it slightly (same topic)
* In topic narrows, simplifying the layout/text to avoid having the awkward `topic narrow` text in the navbar

Other ideas: (to be updated)
* Improving layout and redundancy of information, eg. 
  - don't show stream name above each message, when in a stream narrow

**Comment by Ezio-Sarthak** [comment]
I would like to work on this issue!
They all are great aspects to let the UI match that of webapp :)
