### ISSUE TITLE
Update screenshots before pushing a new release to pypi

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#762]
With `0.5.2` released, our app screenshots are outdated. However, updating them now (in `git`) would mismatch with the one in `pypi` given the fact that `pypi` only generates its project description once per release (see https://github.com/pypa/warehouse/issues/2170).

To avoid this from the next release, we should update our screenshots before pushing a new release to `pypi`.

#### Related files
* [README.md](https://github.com/zulip/zulip-terminal/blob/master/README.md)
* [docs/getting-started.md](https://github.com/zulip/zulip-terminal/blob/master/docs/getting-started.md)

**Comment by neiljp** [comment]
Provisional 0.6.0 screenshot attached.
![pngout](https://user-images.githubusercontent.com/9568999/106058460-1f3f1e80-60a6-11eb-8b70-90ed10bd3d57.png)

**Comment by neiljp** [comment]
Slightly fewer columns:
![pngout](https://user-images.githubusercontent.com/9568999/106060322-b86f3480-60a8-11eb-8f11-2289c78d43f5.png)

**Comment by neiljp** [comment]
Slightly shorter still:
![pngout](https://user-images.githubusercontent.com/9568999/106061037-b659a580-60a9-11eb-8ff8-ea1c54ac9084.png)
