### ISSUE TITLE
Introduce application-wide time format setting

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#770]
Currently, we default to the 24-hour time format in Zulip Terminal. It would be reasonable to introduce an application-wide setting to select between the 12-hour and the 24-hour time format. 

For v1, we might want to introduce it as a custom `zuliprc` setting. (In the web app, it is shown under `Settings > Display settings`.)

Lastly, we would want to discuss which time format should be the _new_ default.

**Comment by neiljp** [comment]
Note that if we can use the API to fetch user settings then we could use that as a reasonable default.

**Comment by aryanshridhar** [comment]
Hey , @neiljp . I looked into the Zulip Api documentation (https://zulip.com/api/get-user) , but I don't see a response type which signifies the user's time-format setting ( Maybe its stored in client side ). Is there something I am missing out ?

**Comment by neiljp** [comment]
@aryanshridhar I believe this is not currently documented in the server. Based on reading `events.py` and `urls.py` in the server, if we were to take the server-fetched approach, we could add an extra string to the initial register call to fetch display settings and then also a handler to update them as events are received - other data/events work in a similar way if you want to look at that. Then we would render based on the value.
