### ISSUE TITLE
Improve styling of compose-message recipients-area

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#783]
Currently we simply have lines around/between eg. stream + topic (+ edit-type), and between that or PM recipients and the message body. In addition we have large 'Stream:  ' and 'Topic:  ' captions, which we could perhaps minimize to look like stream/topic recipients elsewhere in the application, ie. `# stream-name > topic-name`, but with the names being editable.

Later versions of this could color the stream-name once it's validated, and perhaps (if possible) show light 'hint text' in the boxes only when they're empty, eg. `# test here > [blank]` might be shown as `# test here > topic name`, but with the topic name a faded color and the cursor starting at the beginning rather than the end.

**Comment by Ezio-Sarthak** [comment]
@neiljp I would love to work on this issue!
