### ISSUE TITLE
Invalid Credentials when logging in from docker

### ISSUE THREAD

**Issue by fredrikekre** [zulip/zulip-terminal#797]
I get the following error:
```
Invalid Credentials, Please try again!
```
when I try to log in to https://julialang.zulipchat.com from the alpine docker image. I have verified that the credentials work when loggin in from e.g. the browser. Here is the complete "session":
```
$ git clone https://github.com/zulip/zulip-terminal zulip-terminal
[...]

$ cd zulip-terminal/docker/

$ docker build -t zulip-terminal:alpine -f Dockerfile.alpine .
[...]
Successfully tagged zulip-terminal:alpine

$ mkdir $HOME/.zulip

$ docker run -ti -v $HOME/.zulip:/.zulip zulip-terminal:alpine 
zuliprc file was not found at /.zulip/zuliprc
Please enter your credentials to login into your Zulip organization.

NOTE: The Zulip URL is where you would go in a web browser to log in to Zulip.
It often looks like one of the following:
   your-org.zulipchat.com (Zulip cloud)
   zulip.your-org.com (self-hosted servers)
   chat.zulip.org (the Zulip community server)
Zulip URL: https://julialang.zulipchat.com
Email: ekrefredrik@gmail.com
Password: 

Invalid Credentials, Please try again!
```
I also tried with the buster image, but that just crashes on startup:
```
$ docker run -ti -v $HOME/.zulip:/.zulip zulip-terminal:buster 
Traceback (most recent call last):
  File "/home/zulip/zulip-terminal-venv/bin/zulip-term", line 5, in <module>
    from zulipterminal.cli.run import main
  File "/home/zulip/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/cli/run.py", line 10, in <module>
    from urwid import display_common, set_encoding
  File "/home/zulip/zulip-terminal-venv/lib/python3.7/site-packages/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/home/zulip/zulip-terminal-venv/lib/python3.7/site-packages/urwid/widget.py", line 27, in <module>
    from urwid.util import (MetaSuper, decompose_tagmarkup, calc_width,
  File "/home/zulip/zulip-terminal-venv/lib/python3.7/site-packages/urwid/util.py", line 61, in <module>
    detected_encoding = detect_encoding()
  File "/home/zulip/zulip-terminal-venv/lib/python3.7/site-packages/urwid/util.py", line 58, in detect_encoding
    locale.setlocale(locale.LC_ALL, initial)
  File "/usr/local/lib/python3.7/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

Sorry for the low-quality bug report, but I am not sure how to debug this further.

**Comment by fredrikekre** [comment]
I just noticed that I have gotten a bunch of emails with
```
We noticed a recent login for the following Zulip account.

    Organization: https://julialang.zulipchat.com
    Email: 
    Time: 
    Device: An unknown browser on an unknown operating system.
    IP address: 
```
so something seems to have gotten through to the servers.

**Comment by neiljp** [comment]
@fredrikekre Thanks for the report! 

I haven't run with Docker that much recently, but here are some ideas:
* The container generates/loads a zulirpc file as best it can, but it should do it the same inside or outside of docker - so have you tried just using `pipx` or a `virtualenv` setup? (the latter is a lot easier than it used to be, with the `venv` module)
* In that vein, what authentication method do you use to log in? It's possible that you don't have a password set up on your account, eg. if you log in using github (I think we note this in the README)
* How you generate the zuliprc file doesn't matter - if zulip-term generates it that's fine of course, but you can also download a personal zuliprc from the webapp, for example.

Regarding the locale issue, it's possible we should add an environment variable to the docker image, or pass in a language setting from the host.

**Comment by fredrikekre** [comment]
Thanks for the ideas, I managed to login after downloading the pre-populated zuliprc. (BTW, it was pretty difficult to find, it was hidden under API Key). So it looks like what is broken is automatic creation of a zuliprc when noone exists.

> what authentication method do you use to log in?

I have password, and as noted in the OP that password works in the webapp.

**Comment by neiljp** [comment]
@fredrikekre Good to hear that you managed to log in OK in ZT - please let us know of your experience with it and if you have any further troubles or ideas for improvement! I'm not sure if you have an account on chat.zulip.org yet, but feel free to come chat in #**zulip-terminal** :) There have been further updates since the latest pypi release.

@sumanthvrao If you plan to follow up with #571, this would be a good parallel issue to check up on, and fix or document.

**Comment by fredrikekre** [comment]
I think the error is just a file permission error. By default the docker container runs with the `zulip` user https://github.com/zulip/zulip-terminal/blob/5609c78bdc45f972dc1f4bd30399bb6cafe5f332/docker/Dockerfile.alpine#L23 and that one does not have permission to create files in the mapped host folder. Starting the docker container with `-u root` works.

I think the best fix may be to just throw a more descriptive error message that explains this rather than throwing "Invalid credentials".

**Comment by neiljp** [comment]
@fredrikekre This does seem like a permission error, and I'll certainly look at that PR :+1:

To avoid downloading the zuliprc file (or running as root), does `-u <your-local-username>` work for you?

**Comment by fredrikekre** [comment]
> To avoid downloading the zuliprc file (or running as root), does -u <your-local-username> work for you?

No, because there are no user `<your-local-username>` in the container.
