### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by rht** [zulip/zulip-terminal#799]
Travis-CI.org will be shut down on December 31, 2020: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D

Migration instructions here: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

Also remember to update the Travis badge in the README.md.

Make sure to read the discussion at: https://chat.zulip.org/#narrow/stream/2-general/topic/Travis-CI.2Eorg.20shuts.20down.20on.20December.2031.2C.202020

**Comment by sumagnadas** [comment]
This is going to be my first time contributing to zulip-term. So what am I supposed to do here?

**Comment by amanagr** [comment]
@sumagnadas you need to read the doc liked in the comment and apply changes to our travis.yml file. Also, do read https://zulip.readthedocs.io/en/latest/overview/contributing.html

**Comment by sumagnadas** [comment]
It doesn't seem like the .travis.yml file needs any fixing. It seems like it is mostly the migration and updating the link of the Travis badge in README.md.

**Comment by sumagnadas** [comment]
@zulipbot claim

**Comment by sumagnadas** [comment]
Someone has to start the migration before the badge's link in README.md is updated. After migration, someone can update the README.md(or I can if there's no problem about that. 

I had my profile in travis-ci.com and I forked this repo. I started the build and it didn't fail so it doesn't seem like the .travis.yml needs to be updated

**Comment by timabbott** [comment]
It seems like Travis CI hasn't fully implemented their migration process (I clicked the "apply for the beta" button; we'll see what comes of that).

**Comment by neiljp** [comment]
@timabbott The process appear multi-step - for my personal account I tried various options, but I think I went to the .com and migrated things over in various stages.

**Comment by timabbott** [comment]
I believe I did the migration step I need to do for this.

**Comment by neiljp** [comment]
@timabbott Thanks!

Anyone want to take up the related changes?

**Comment by neiljp** [comment]
@andersk You just pushed all the changes necessary to fix this, at least for ZT?

**Comment by andersk** [comment]
I updated the Travis badge in 01734667c85be4d46444e51f2f85b8a9b18e1815. I think that’s all we need to do.
