### ISSUE TITLE
Migrate 'all messages' key to 'a' in UI (retaining current key)

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#804]
The webapp is likely to move to a default view of recent topics in the future, meaning that all-messages will acquire a dedicated key since it is not the default view (associated with `esc`) any longer.

While ZT does not have an interface for recent-topics, it would be beneficial to at least support the new key for all-messages. Even if the webapp chooses not to take this path, it could be useful to migrate away from using `esc` for so many actions, and improve (partially automatic) documentation of how to narrow to all messages.

This will require updating the keybindings and ensuring that this works for both `esc` and `a`, and checking that the UI renders for `a` only. This key may be hardcoded right now, so a new keybinding entry may be needed (to appear in the correct place in the help menu), and referred to in appropriate places in the code. The README should also be updated accordingly.

The intention is that users migrate to this keybinding in the near term via the advertised key. At a later stage we might remove the `esc` key completely, and we could open an issue for this following resolution of this issue.

**Comment by adwait-thattey** [comment]
@zulipbot claim

**Comment by adwait-thattey** [comment]
> This will require updating the keybindings and ensuring that this works for both esc and a, and checking that the UI renders for a only.

@neiljp  Slightly confused on this. Does this mean all messages should show on pressing both 'a' and 'Esc' or should they appear only on 'a'
