### ISSUE TITLE
Fetch realm emoji in initial register call & update using events

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#809]
We have preliminary support for realm emoji (custom emoji specific to an organization) via #710, but this has a few caveats (though perhaps minor, depending on the frequency of adding custom emoji vs each ZT session):
* We don't update the realm emoji ZT is aware of, using events available from the server
* We fetch using an API call after initial register, so even if we had updates, we might miss them between the two points - we should really just grab them out of the initial register() call (initial_data) instead

Working on this issue is a fairly good introduction to how the Zulip events API works. You'll likely want to review the events in the zulip documentation and existing code in `model.py`, which is where event handling occurs.

**Comment by mkp6781** [comment]
I am new to the codebase and this is my first issue.
From what I have understood, these are the changes I intend to make:
- add "realm_emoji" to fetch_event_types list
-  change line 148 in `__init__` models.py from`        custom_emoji_data = self.fetch_custom_emojis()
` to
`        custom_emoji_data = self.initial_data['realm_emoji']
`

When a client starts up, a call to `_update_initial_data()`is made which in turn calls `_register_desired_events()` Here the list of events in `fetch_event_types()` gets registered to the event queue. Finally the `initial_data` is updated with values in the returned `response` .
Please correct me if I've gone wrong.

**Comment by neiljp** [comment]
@mkp6781 What you've described should replace the existing code and is related to the first part of this issue (title - the second bullet).

The second part (of title, the first bullet) - "update using events" - requires an event handler for that event type to update them as emoji are added and removed on the server, so that the application retains a current list.

**Comment by mkp6781** [comment]
```python  
 def _handle_update_emoji_event(self, event: Event) -> None:
        """
        Handle update of emoji
        """
        realm_emojis = event['realm_emoji']
        self.active_emoji_data.update(realm_emojis)
```
This is the event handler code. However when I run pytest, it gives me a 'key error' saying no key 'realm_emoji'.  Should I make any more changes to pass the tests?

**Comment by neiljp** [comment]
The `Event` type likely doesn't have that key at this point. You also should check whether it *should* have that key, based on the different types of events available from the Zulip API.

https://zulip.com/api/get-events#realm_emoji-update

You're just quoting a function here so I'm not sure what else you've written, but note that this method won't be triggered unless you map the function to the name of the event type, as with the other event handlers.

Also note that you likely need to adjust the event data to understand what change to make to the emoji data.

**Comment by mkp6781** [comment]
Shall I open a pull request so that you can do a quick review?
Thanks!

**Comment by mkp6781** [comment]
Pull request #827

**Comment by Ezio-Sarthak** [comment]
Hi @neiljp I am new to the codebase and this is my first issue. Could you please elaborate a bit what the issue is?

**Comment by mkp6781** [comment]
I have updated the pr. #827 
Please do have a look and suggest any more changes that may be necessary.

**Comment by mkp6781** [comment]
@zulipbot claim

**Comment by neiljp** [comment]
@Ezio-Sarthak Someone is already working on this right now - have a look at other issues, explore the application and see what you think could be improved, and come and have a chat on chat.zulip.org in #**zulip-terminal** :)

**Comment by Ezio-Sarthak** [comment]
@neiljp Yeah sure, thanks!

**Comment by mkp6781** [comment]
@zulipbot add "PR needs review"
