### ISSUE TITLE
Show configuration options for current session in about popup

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#812]
Once the application is running we don't have a way to establish which options ZT was loaded with.

We already have the about window, so having this in an "Application configuration" section in that window would be convenient.

**Comment by zee-bit** [comment]
Hi @neiljp,
I have managed to implement this feature enhancement. Here is the screenshot:
![About-section-zt](https://user-images.githubusercontent.com/54993043/98036151-8cdd0500-1e3f-11eb-8f38-686f5029b948.png)
This is my first contribution to Zulip's codebase, let me know if any thing needs to be modified. Also, before I make a PR, I just wanted to know is there any test or linting that I need to perform locally?
Thanks

**Comment by neiljp** [comment]
@zee-bit That looks good as a first step - we can always adjust from within a PR :) 
(I'm unsure if we want to have configuration above or below the server details, but it looks good for now :+1:)

For linting, it depends on your dev setup - if you used `make` to build your environment then you can use `make check`. That runs `tools/lint-all` and `pytest`, which can both be run individually, whether you used `make` to construct your virtual environment or not.
