### ISSUE TITLE
Adding Issue + PR Templates

### ISSUE THREAD

**Issue by HarshCasper** [zulip/zulip-terminal#830]
## Description 

- Add an Issue Template to streamline creating new Issues 
- Add a PR Template to document the changes implemented. 

I would like to work on the same. This would make it easy for the reviewers to review the important points of the PR and make necessary request changes for them.

**Comment by neiljp** [comment]
@HarshCasper Thanks for opening this issue!

Re issue templates, I've noticed some other projects/repos now use the github feature of multiple templates, which helps triage feedback and focus the information requested. While we could support a basic issue template first, the breadth expected likely would make this noisy.

Re PR templates, this seems feasible to work on more directly, though needs review of the existing formats and requests that we typically make of contributors.

I'd welcome your work on this issue, though this may end up needing quite some fine-tuning by contributors more experienced with the project.

**Comment by neiljp** [comment]
I listed some example issue types in #**zulip-terminal>Issue types** for open discussion on chat.zulip.org.

**Comment by neiljp** [comment]
Now that ZT is becoming more popular, I'm bumping the priority of this.

**Comment by neiljp** [comment]
The pull request template has gone through various iterations already, so with #1488 or a followup, this issue will be resolved.

**Comment by neiljp** [comment]
Since we now have a structure in place from #1488, I'm going to close this - there will always be iterations we can do in future!
