### ISSUE TITLE
Message editing: Add support for renaming of "(no topic)" messages

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#837]
We currently support editing message topics of one or many messages, but only via one's own messages in those topics.

If a topic is "topicless", ie. shown as "(no topic)", then depending on server settings it should be possible to edit it independently of contribution to the topic:
https://zulip.com/help/configure-message-editing-and-deletion

**Comment by Ezio-Sarthak** [comment]
I'd love to work on this issue!

**Comment by zee-bit** [comment]
@Ezio-Sarthak are you still working on this or can I take this up?

**Comment by Ezio-Sarthak** [comment]
@zee-bit Sure, you can take it up 👍
