### ISSUE TITLE
How to login using Github OAuth?

### ISSUE THREAD

**Issue by shubhank-saxena** [zulip/zulip-terminal#842]
I have used Github OAuth method to signup/login in a zulip server. How do to it in the CLI? It's asking for email and password

**Comment by neiljp** [comment]
@shubhank-saxena Thanks for giving ZT a try and asking the question :+1: Unfortunately right now we only support email/password as a means of accessing the user profile and generating a zuliprc from within ZT. It is possible that if you download your personal zuliprc file via the web interface and point ZT at that file it may work, but I don't have personal experience with that.

This would likely be one element of #631.

**Comment by shubhank-saxena** [comment]
Thank you so much for the reply @neiljp :+1:

**Comment by neiljp** [comment]
@shubhank-saxena Let me know if you manage to login with ZT, and whether with ZT or another client you're welcome to drop by #**zulip-terminal** on chat.zulip.org :)

As per the issue I referenced, this is something we'd like to add in future.

**Comment by neiljp** [comment]
Closing this in favor of #631.
