### ISSUE TITLE
Addition of pre-commit

### ISSUE THREAD

**Issue by shubhank-saxena** [zulip/zulip-terminal#843]
Every time that someone lands up a PR, the person is expected to run the lint tests. And if they fail to do so, it may result in failure of Travis. And then they will have to re-run the test and push back again.
How about we add a pre-commit hook, which will ensure that all the lint tests are run before being committed to the branch/repo and thus saving the time!
Tool to use - https://pre-commit.com/

**Comment by Ezio-Sarthak** [comment]
Hi @shubhank-saxena ! I guess this is already documented here: [Zulip's Git pre-commit hook]](https://zulip.readthedocs.io/en/latest/git/zulip-tools.html#set-up-git-repo-script) :)

**Comment by shubhank-saxena** [comment]
Oh. I must have missed it. Thanks for pointing it out @Ezio-Sarthak
