### ISSUE TITLE
Improve compose hotkey behavior (as compared to replies)

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#871]
Most of the compose-message actions behave fairly well, and many are reply-based, often with extra features.

Since our autocomplete of streams/topics has been (and for users still is) less useful, the best approach for ZT users has been to rely upon ways to reply, rather than do straight compose actions. For example, one might go to a stream or topic and reply but editing the stream/topic, or reply to a user in PMs, or by using the user list.

Now that we have autocomplete for stream/topic in the compose header, this is already a lot better, and hopefully we will have this for PMs soon too #587. **Before we do, we should ensure that non-reply compose works well.**

* [ ] Currently r/enter and other keys work fine for replying, but x/c seem not quite right - in particular `c` while in a PM narrow.
* [ ] We can expand non-replying compose (x/c) to many other contexts - they should work almost everywhere?

**Comment by jalajcodes** [comment]
I would like to work on this but as I am still getting familiar with ZT and it's codebase it might take me some time  to understand what needs to be done and how.

**Comment by mkp6781** [comment]
I would like to work on this issue. On taking a look, it seems that <kbd>x</kbd> is working fine while <kbd>c</kbd> is creating the wrong compose box. Is this the issue that needs to be resolved here?
