### ISSUE TITLE
Automate developer overview of files by extracting module docstrings

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#892]
Currently overviews of each file are manually described in `docs/developer-file-overview.md`.

For developers it would be useful to have each of these descriptions at the top of a given file as a docstring; with that, this document could then be generated automatically and checked to be up to date in CI.

* [x] Add docstrings to each source file that match the overview file
* [ ] Add a CI Action which ensures the document matches the expectations from the docstrings
* [x] Generate the document from docstrings rather than manually

**Comment by Abhirup-99** [comment]
I would love to work on this issue.

**Comment by neiljp** [comment]
Parts of this are resolved by the docstrings and generation present by the already-merged part of #1208 - Thanks @mounilKshah 🎉 

The remaining steps are to enable linting, both locally (like the rest of #1208) and ultimately in CI too.

**Comment by neiljp** [comment]
#1208 fixed the first and last checkboxes and auto-closed this, but I just merged #1254 to fix the remaining checkbox (add CI).
