### ISSUE TITLE
Show sender/recipient presence status in messages

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#896]
This is to clarify the intent behind PR #501, which isn't quite #406 (related to highlighting particular users eg. yourself vs others by name), but more to translate the presence information into an extra field in messages to avoid scanning through the user list to see the sender's active status. We could also apply this to recipients in PMs.

**Comment by neiljp** [comment]
The server has some aspect of this (eg. in list of PMs) and is considering more, starting with perhaps zulip/zulip#17137, zulip/zulip#17138 and PR zulip/zulip#17149.

More discussion here:
https://chat.zulip.org/#narrow/stream/137-feedback/topic/Status.20Evidence

**Comment by Ezio-Sarthak** [comment]
@neiljp Thanks for opening the corresponding issue separately!

Would love to work on it!

**Comment by mkp6781** [comment]
@Ezio-Sarthak Can I take this up if you have not working on this?

**Comment by Ezio-Sarthak** [comment]
@mkp6781 I just thought of pushing a PR for this a while ago, before I got occupied with other issues. I (vaguely) remember I have a remote branch for this, and looking forward to revive and push the work ASAP 😅. Thanks for querying 👍. I hope I'm able to clarify 😅
