### ISSUE TITLE
KeyError: 'flags'

### ISSUE THREAD

**Issue by klfoulk16** [zulip/zulip-terminal#920]
![Screen Shot 2021-02-12 at 8 38 22 PM](https://user-images.githubusercontent.com/57010984/107838385-ac0afd00-6d73-11eb-935f-14d38cce2ee2.png)

The following error was in my zulip-terminal-thread-exceptions.log:

Traceback (most recent call last):
  File "/Users/kellyfoulk/Documents/code/zulip-terminal/zulipterminal/model.py", line 1265, in poll_for_events
    self.event_actions[event['type']](event)
  File "/Users/kellyfoulk/Documents/code/zulip-terminal/zulipterminal/model.py", line 1124, in _handle_update_message_flags_event
    if flag_to_change not in msg['flags']:
KeyError: 'flags'

I was not doing anything in the terminal when this appeared. I had been on my browser and when I moved back to the terminal this was showing on the screen. This was about 1.5 hours after I had issue #919 occur and it was within the same zulip-terminal instance.

Running Zulip Terminal 0.6.0+git on mac in a Z shell

**Comment by dehnert** [comment]
I also hit this, but don't know why. (Zulip-Terminal in screen in Gnome Terminal, checked out from git today.)

**Comment by zee-bit** [comment]
Bumping the priority, since I happened to encounter the same bug twice today. Trying to figure out a quick fix too...

**Comment by neiljp** [comment]
After a little debugging, I can now reproduce this via:
- open ZT
- use another client (eg. webapp) to react to a message not currently cached by ZT
- again outside of ZT, star/unstar that same message

A small fix appears to resolve this well, and I'm going to do a small PR and merge shortly, though we may want to consider our use of defaultdict more generally, at least in certain datastructures.
