### ISSUE TITLE
Autocomplete mention with spaces between first and last names

### ISSUE THREAD

**Issue by ahmedabuamra** [zulip/zulip-terminal#925]
Mentioning a user with first name OR last name only works fine, but when trying to autocomplete mentioning them with full name, the autocomplete suggest users based on the last name only (assuming putting the cursor at the end of the last name) while it should use the words before the last name in suggestions too.

**Comment by avats-dev** [comment]
Can anyone help me out how this could be resolved?

**Comment by avats-dev** [comment]
Hii, any updates or tips on this?

**Comment by Ezio-Sarthak** [comment]
@avats-dev Apologies for the slow reply. I'm afraid you've understood the issue correctly?

I think the issue description might need some improvements, as the autocomplete doesn't seem to show any results for full names?

Hop in anytime in [#zulip-terminal](https://chat.zulip.org/#narrow/stream/206-zulip-terminal) stream on czo. Feel free to discuss any issue/bug/problems etc in the community :)

**Comment by neiljp** [comment]
@avats-dev Are you asking as a user or a potential contributor?

The solution may involve dynamically updating the delimiter which urwid-readline provides, but that's just an idea based on the approach I took to resolve this with autocomplete with spaces in the stream header, which is a lot simpler than general autocomplete in a body of text.
